#!/usr/bin/env python3
"""Regenerate every table in RECOVERY_TWOSIDED.md from the raw JSON.

The tables are GENERATED, not hand-typed — a hand-typed table is a transcription
error waiting to be quoted.  ``python3 code/tables.py raw > artifacts/tables.md``
"""
from __future__ import annotations

import json
import sys
from pathlib import Path


def load(d, name):
    return json.loads((Path(d) / f"{name}.json").read_text(encoding="utf-8"))


def fmt_ci(c, nd=4):
    if c is None:
        return "—"
    return f"{c['delta']:+.{nd}f} [{c['lo']:+.{nd}f}, {c['hi']:+.{nd}f}] " \
           f"{'**SEP**' if c['separated'] else 'n.s.'}"


def main(d):
    inj = load(d, "injections")["injections"]
    rep = load(d, "repro_gate")["repro_gate"]
    pan = load(d, "panel_both_terms")["panel_both_terms"]
    sat = load(d, "saturation_census")["saturation_census"]
    aud = load(d, "term_audit")["term_audit"]
    shp = load(d, "shape_sensitivity")["shape_sensitivity"]
    o = print

    o("# Generated tables — `2026-07-28-recovery-twosided`\n")
    o("*Every table below is regenerated by `code/tables.py` from `raw/*.json`.*\n")

    # ---- T1 the acceptance test ------------------------------------------- #
    o("\n## T1 — ⭐ THE ACCEPTANCE TEST: the 8 injections, every shape\n")
    o("| shape | correct direction | verdict | max recovery floor frac |")
    o("|---|:--:|:--:|--:|")
    for s, n in inj["shapes"].items():
        ff = shp["shapes"].get(s, {}).get("recovery_floor_frac_max")
        o(f"| `{s}` | **{n['n_correct']}/{n['n_total']}** | "
          f"{'✅ PASS' if n['ALL_8_CORRECT'] else '⛔ FAIL'} | "
          f"{'—' if ff is None else f'{ff:.4f}'} |")

    for s in ("clamp_v1", "twosided_v2" if "twosided_v2" in inj["shapes"]
              else "lin_q0p6667"):
        if s not in inj["shapes"]:
            continue
        o(f"\n### T1.{1 if s == 'clamp_v1' else 2} — per cell, `{s}`\n")
        o("| arm | injection | zero-mean | Δ`recovery` | Δ`ego_progress` "
          "| **Δ composite** | correct? |")
        o("|---|---|:--:|--:|--:|---|:--:|")
        for k, v in inj["shapes"][s]["cells"].items():
            arm, ctl = k.split("|")
            o(f"| `{arm}` | `{ctl}` | {'⭐ yes' if v['zero_mean_control'] else ''} "
              f"| {v['recovery']['delta']:+.4f} "
              f"| {v['ego_progress']['delta']:+.4f} "
              f"| {fmt_ci(v['PSS_composite'])} "
              f"| {'✅' if v['CORRECT_DIRECTION'] else '⛔'} |")

    # ---- T2 charge rate ---------------------------------------------------- #
    ch = inj["charge_rate"]
    o("\n## T2 — ⭐⭐ THE MECHANISM: charge rate `|dg/dr|` where the data lives\n")
    o(f"*Panel ratio: median **{ch['panel_ratio_median']}**, p90 "
      f"{ch['panel_ratio_p90']}, fraction > 1 = "
      f"**{ch['panel_ratio_frac_gt_1']:.1%}**.*\n")
    o("| shape | r=0 | r=0.5 | r=1 | r=2 | r=3 | row-weighted | "
      "reward bias (near-perfect ÷ median) | injections correct |")
    o("|---|--:|--:|--:|--:|--:|--:|--:|:--:|")
    for s, v in ch["shapes"].items():
        rb = v["reward_bias_near_perfect_over_median"]
        rbs = "∞" if rb > 1e6 else f"{rb:.2f}"
        n = inj["shapes"].get(s, {})
        o(f"| `{s}` | {v['slope_at_r0']:.4f} | {v['slope_at_r0p5']:.4f} "
          f"| {v['slope_at_r1']:.4f} | {v['slope_at_r2']:.4f} "
          f"| {v['slope_at_r3']:.4f} | {v['row_weighted_mean_slope']:.4f} "
          f"| **{rbs}** | {n.get('n_correct', '—')}/8 |")

    # ---- T3 repro ---------------------------------------------------------- #
    o("\n## T3 — ✅ THE REPRODUCTION GATE\n")
    o(f"| | |\n|---|---|")
    o(f"| published `@clamp_v1` composites checked | **{rep['n_checked']}** |")
    o(f"| **max \\|diff\\|** | ⭐ **{rep['max_abs_diff']:.6f}** |")
    o(f"| verdict | {'✅ **PASS**' if rep['PASS'] else '⛔ **FAIL**'} |")
    o(f"| metric id must be unchanged | `{rep['metric_id_must_be_unchanged']}` |")
    o(f"| `clamp_v1` bit-identical to `lin_q0` | "
      f"{'✅' if rep['clamp_v1_is_bit_identical_to_lin_q0'] else '⛔'} |")
    o("\n| arm | published | recomputed | \\|diff\\| |")
    o("|---|--:|--:|--:|")
    for k, v in rep["per_arm"].items():
        if "got" not in v:
            continue
        o(f"| `{k}` | {v['published']:.4f} | {v['got']:.4f} "
          f"| {v['abs_diff']:.6f} |")

    # ---- T4 the panel ------------------------------------------------------ #
    o("\n## T4 — THE PANEL UNDER BOTH RECOVERY TERMS\n")
    o(f"*Published id `{pan['published']['metric_id']}` · "
      f"new id `{pan['new']['metric_id']}`.* ⛔ **Levels are NOT comparable "
      f"across ids.**\n")
    o("| rank (new) | arm | `rec@clamp_v1` (PUBLISHED) | `rec@twosided_v2` (NEW) "
      "| Δ | rank (pub) | `recovery` pub → new | floor frac pub → new |")
    o("|--:|---|---|---|--:|--:|---|---|")
    L, N = pan["published"]["levels"], pan["new"]["levels"]
    order = [r["arm"] for r in pan["ranking_new"]["all_non_probe"]]
    order += [a for a in N if a not in order]
    po = [r["arm"] for r in pan["ranking_published"]["all_non_probe"]]
    for i, a in enumerate(order):
        if a not in L:
            continue
        pr = po.index(a) + 1 if a in po else "—"
        fp = L[a]["recovery_saturation"]["floor_frac_le_0p001"]
        fn = N[a]["recovery_saturation"]["floor_frac_le_0p001"]
        o(f"| {i + 1 if a in po else '—'} | `{a}` "
          f"| {L[a]['mean']:.4f} [{L[a]['lo']:.4f}, {L[a]['hi']:.4f}] "
          f"| {N[a]['mean']:.4f} [{N[a]['lo']:.4f}, {N[a]['hi']:.4f}] "
          f"| {N[a]['mean'] - L[a]['mean']:+.4f} | {pr} "
          f"| {L[a]['recovery']:.4f} → {N[a]['recovery']:.4f} "
          f"| {'—' if fp is None else f'{fp:.4f}'} → "
          f"{'—' if fn is None else f'{fn:.4f}'} |")

    o("\n## T5 — THE PAIRED CONTRASTS\n")
    kn = [k for k in next(iter(pan["contrasts"].values())) if k.startswith("new_")][0]
    o("| contrast | Δ under `rec@clamp_v1` (PUBLISHED) | Δ under `rec@twosided_v2` "
      "(NEW) | flip? |")
    o("|---|---|---|:--:|")
    for k, v in pan["contrasts"].items():
        o(f"| `{k}` | {fmt_ci(v['published_rec_clamp_v1'])} | {fmt_ci(v[kn])} "
          f"| {'⛔ **YES**' if v['verdict_flipped'] else ''} |")

    rs = pan["RANKING_STATEMENT"]
    o("\n## T6 — THE RANKING STATEMENT\n")
    o("| question | answer |\n|---|---|")
    o(f"| `cv_holdv0` rank among realisable arms, PUBLISHED | "
      f"**{rs['cv_holdv0_rank_realisable_published']}** |")
    o(f"| `cv_holdv0` rank among realisable arms, NEW | "
      f"**{rs['cv_holdv0_rank_realisable_new']}** |")
    o(f"| ⭐ **does `cv_holdv0` still rank FIRST among realisable arms?** | "
      f"**{'YES' if rs['cv_holdv0_STILL_RANKS_FIRST_AMONG_REALISABLE'] else 'NO'}** |")
    o(f"| whole v1 TACTICAL family below every REF-C arm, PUBLISHED | "
      f"**{'YES' if rs['whole_v1_tactical_family_below_every_REFC_published'] else 'NO'}** |")
    o(f"| ⭐ **whole v1 TACTICAL family below every REF-C arm, NEW** | "
      f"**{'YES' if rs['whole_v1_tactical_family_below_every_REFC_new'] else 'NO'}** |")
    o(f"| realisable arms whose rank moved | {rs['n_realisable_arms_that_moved']} |")
    o(f"| non-probe arms whose rank moved | {rs['n_non_probe_arms_that_moved']} |")
    o(f"| level shift, min → max | +{rs['level_shift_min']:.4f} → "
      f"+{rs['level_shift_max']:.4f} |")

    # ---- T7 saturation ----------------------------------------------------- #
    o("\n## T7 — ⚠️ SATURATION BESIDE EVERY BOUNDED TERM (C45's standing "
      "consequence)\n")
    cols = ["ego_progress@twosided_v2", "recovery@clamp_v1",
            "recovery@twosided_v2", "comfort", "lon_track", "lat_track",
            "lat_heading"]
    o("| arm | " + " | ".join(f"`{c}`" for c in cols) + " |")
    o("|---|" + "--:|" * len(cols))
    for a in sorted(sat["per_arm"]):
        cells = []
        for c in cols:
            n = sat["per_arm"][a].get(c, {})
            f = n.get("floor_frac_le_0p001")
            ce = n.get("ceiling_frac_ge_0p999")
            if f is None:
                cells.append("—")
            else:
                mark = "⛔" if max(f, ce or 0) >= sat["_warn_frac"] else ""
                cells.append(f"{mark}{f:.4f}/{ce:.4f}")
        o(f"| `{a}` | " + " | ".join(cells) + " |")
    o(f"\n*cells are* `floor_frac / ceiling_frac` *over DEFINED rows; ⛔ marks "
      f"≥ {sat['_warn_frac']:.0%} on either side. Gate thresholds: floor "
      f"{sat['_gate_thresholds']['floor_frac_max']}, ceiling "
      f"{sat['_gate_thresholds']['ceil_frac_max']}.*")

    # ---- T8 the term audit ------------------------------------------------- #
    o("\n## T8 — ⛔ THE AUDIT OF EVERY REMAINING TERM\n")
    o("| term | clamped side(s) | max floor frac over panel | worst arm | "
      "one-sided risk? |")
    o("|---|---|--:|---|:--:|")
    for k, v in aud["terms"].items():
        fp = {a: f for a, f in v["floor_frac_per_arm"].items() if f is not None}
        worst = max(fp, key=fp.get) if fp else "—"
        o(f"| `{k}` | {v['clamped_sides']} | "
          f"**{v['floor_frac_max_over_panel']:.4f}** | `{worst}` | "
          f"{'⛔ **YES**' if v['ONE_SIDED_RISK'] else '✅ no'} |")

    # ---- T9 shape sensitivity ---------------------------------------------- #
    o("\n## T9 — THE RANKING'S SENSITIVITY TO THE SHAPE\n")
    shapes = list(shp["shapes"])
    arms = [r["arm"] for r in shp["shapes"][shapes[0]]["ranking_realisable"]]
    o("| arm | " + " | ".join(f"`{s}`" for s in shapes) + " |")
    o("|---|" + "--:|" * len(shapes))
    for a in arms:
        cells = []
        for s in shapes:
            rk = next((r["rank"] for r in shp["shapes"][s]["ranking_realisable"]
                       if r["arm"] == a), None)
            lv = shp["shapes"][s]["levels"].get(a)
            cells.append("—" if lv is None else f"#{rk} {lv:.4f}")
        o(f"| `{a}` | " + " | ".join(cells) + " |")
    rb = shp["ROBUSTNESS"]
    o(f"\n* rank-1 realisable arm is the SAME under every shape: "
      f"**{rb['rank1_is_the_same_under_every_shape']}** "
      f"({sorted(set(rb['rank1_realisable_per_shape'].values()))})")
    o(f"* the FULL realisable order is identical under every shape: "
      f"**{rb['full_order_identical_under_every_shape']}**")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "raw")
