"""WP-L — is the trunk's VRU failure a POOLING artifact, a LINEARITY artifact, or real?

⛔ WHY THIS RUNS BEFORE A DISTILLATION HEAD IS BUILT. WP-I v3 (verified join, 33
episodes) found DINOv3 the only arm clearing its own within-episode null on agent
presence, with REF-C's trunk at **p_w 0.110, adj +0.0943** on the near band --
close, but not across. That number was measured through TWO lossy choices that
are mine, not the model's:

    1. the trunk's [704, 8, 8] map was average-pooled to a 2x4 GRID
    2. it was read by a LINEAR ridge

⚠️ `CLAUDE.md`: *a negative from a linear probe is not a negative about
learnability* -- the implication runs one way only. And WP-J already proved this
programme can mistake a pooling choice for a representational fact.

⭐ THE DECISION THIS SETTLES, and it decides all of stage C:
  * if a FINER GRID rescues the trunk  -> the deficit is SPATIAL, and a
    distillation head would be solving a pooling problem, not a semantics one;
  * if a NONLINEAR kernel rescues it   -> the information is present but not
    linearly separable, and the reasoner's own MLP can reach it for free;
  * if NEITHER does                    -> the trunk genuinely lacks agent
    presence and distillation is the right lever.

⭐ HOW THE NONLINEAR ARM IS AFFORDABLE: the panel already solves ridge in the
DUAL (Gram) form, and a dual solve does not care whether the Gram matrix came
from a dot product or a kernel. Swapping `A @ A.T` for an RBF kernel turns the
same machinery into kernel ridge -- same folds, same lambda selection, same
permutation nulls, no new estimator to validate.

ARMS (all on the SAME windows, SAME targets, SAME folds):
    trunk 2x4  linear   <- the WP-I v3 baseline, reproduced here as the anchor
    trunk 8x8  linear   <- the FULL feature map, zero spatial pooling loss
    trunk 2x4  rbf      <- nonlinearity at the baseline's resolution
    trunk 8x8  rbf      <- both levers at once
    dinov3 2x4 linear   <- the reference that DID clear the null

⛔ CONTROLS, unchanged so the panel stays comparable to WP-I v3:
  * CONSTANT-only            must read 0.5000 EXACTLY
  * PC-TRUNK (REF-C's own selected-anchor lateral sign)  every TRUNK arm must
    win it decisively; if a trunk arm cannot read REF-C's own decision, that
    arm's features or kernel are broken and its VRU null result is unreadable
  * permutation nulls, global AND within-episode, generated by this pipeline
  * within-null centres PRINTED, never gated (the gate defect fixed in v3)
  * gamma AND lambda chosen inside each fold's training data only

Join: `pilot_val_agents_ext.jsonl` (identity verified by content registration).
NO_LABEL frames masked. Tier T0, NON-PARITY pilot. Evidence class MEASURED (ours).
"""
import collections
import importlib.util
import io as _io
import json
import math
import sys
import time

import numpy as np
import torch

sys.path.insert(0, "stack")
_s = importlib.util.spec_from_file_location("pilot", "stack/scripts/rl_pilot_refc21.py")
P = importlib.util.module_from_spec(_s)
_s.loader.exec_module(P)

O = r"C:/Users/Admin/tanitad-data/rl-pilot"
DEV = "cuda" if torch.cuda.is_available() else "cpu"
NEAR_M, FAR_M = 20.0, 60.0
HALF = math.atan(128.0 / 266.0)
MAX_PER_EP = int(sys.argv[1]) if len(sys.argv) > 1 else 60
N_PERM = int(sys.argv[2]) if len(sys.argv) > 2 else 200
JOIN = O + "/pilot_val_agents_ext.jsonl"
VRU = {"person", "rider", "stroller", "animal"}

from tanitad.refs import refc as _refc                                    # noqa: E402

model = _refc.RefCModel(_refc.refc_config())
_ck = torch.load(r"C:/Users/Admin/tanitad-data/models/refc-base-30k/ckpt.pt",
                 map_location="cpu", weights_only=False)["model"]
_r = model.load_state_dict(_ck, strict=False)
assert set(_r.missing_keys) == {"decoder.anchor_controls"}, _r.missing_keys
model = model.to(DEV).eval()

from transformers import DINOv3ViTModel                                   # noqa: E402

dino = DINOv3ViTModel.from_pretrained(
    "facebook/dinov3-vitl16-pretrain-lvd1689m", dtype=torch.bfloat16).to(DEV).eval()
IMN_M = torch.tensor([0.485, 0.456, 0.406], device=DEV).view(1, 3, 1, 1)
IMN_S = torch.tensor([0.229, 0.224, 0.225], device=DEV).view(1, 3, 1, 1)
PATCH = int(dino.config.patch_size)

raw = collections.defaultdict(dict)
TS = collections.defaultdict(dict)
for line in _io.open(JOIN, encoding="utf-8"):
    d = json.loads(line)
    raw[d["clip_id"]][d["frame_idx"]] = d["agents"]
    TS[d["clip_id"]][d["frame_idx"]] = float(d["t_s"])
_meta = json.load(_io.open(JOIN + ".meta.json", encoding="utf-8"))
SPAN = {e["stem"]: e["label_span_s"] for e in _meta["identity_log"]
        if e.get("mode") == "registered" and e.get("label_span_s")}

src = P.WindowSource(
    r"C:/Users/Admin/tanitad-data/physicalai/_epcache/physicalai-val-bb543bdf7836",
    JOIN, seed=0, lru=6)

FMAP, DINO, TGT, EPS = [], [], collections.defaultdict(list), []
n_masked = 0
rng = np.random.default_rng(1234)
t0 = time.time()
with torch.no_grad():
    for si, stem in enumerate(src.stems):
        key = next((k for k in raw if k in stem or stem in k), None)
        if key is None:
            continue
        T = int(src._ep(stem)["poses"].shape[0])
        lo, hi = P.WINDOW - 1, T - P.HORIZONS[-1] - 1
        for t in sorted(rng.choice(np.arange(lo, hi),
                                   size=min(MAX_PER_EP, hi - lo), replace=False)):
            t = int(t)
            ags = raw[key].get(t)
            if ags is None:
                continue
            sp, ts = SPAN.get(key), TS[key].get(t)
            if sp is not None and ts is not None and not (sp[0] <= ts <= sp[1]):
                n_masked += 1
                continue
            w = src.window(stem, t)
            if w is None:
                continue
            b = P.collate([w], DEV)
            f9 = b["frames"][0, -1]
            fm = model.encoder(b["frames"][:, -1])
            fm = (fm[0] if isinstance(fm, (tuple, list)) else fm)[0]   # [704,8,8]
            # ⭐ the FULL map is banked once; every grid below is derived from it
            # by pooling, so all pooling arms see literally the same features.
            FMAP.append(fm.float().cpu().numpy().astype(np.float32))
            gh, gw = f9.shape[-2] // PATCH, f9.shape[-1] // PATCH
            outs = []
            for k in range(3):
                img = ((f9[3 * k:3 * k + 3].unsqueeze(0) - IMN_M) / IMN_S).bfloat16()
                h = dino(pixel_values=img).last_hidden_state[0].float()
                tok = h[h.shape[0] - gh * gw:].reshape(gh, gw, -1).permute(2, 0, 1)
                outs.append(torch.nn.functional.adaptive_avg_pool2d(tok, (2, 4)).flatten())
            DINO.append(torch.cat(outs).cpu().numpy().astype(np.float32))

            def seen(a):
                return a["cx"] > 0 and abs(math.atan2(a["cy"], a["cx"])) <= HALF

            TGT["vru<20m IN-FOV"].append(float(any(
                a.get("cls") in VRU and 0 < a["cx"] < NEAR_M and abs(a["cy"]) <= 4.0
                and seen(a) for a in ags)))
            TGT["vru<60m IN-FOV"].append(float(any(
                a.get("cls") in VRU and 0 < a["cx"] < FAR_M and abs(a["cy"]) <= 4.0
                and seen(a) for a in ags)))
            out = model(b["frames"], None, b["v0"], steps=2)
            sel = int(out["sel_score"][0].argmax())
            TGT["PC-TRUNK sel lateral>0"].append(
                float(float(out["anchor_traj"][0, sel, -1, 1]) > 0))
            EPS.append(stem)
        print("[wpl] ep %d/%d %s: %d windows (%.0f s)"
              % (si + 1, len(src.stems), stem, len(EPS), time.time() - t0), flush=True)

FMAP = np.asarray(FMAP)                      # [N, 704, 8, 8]
DINO = np.asarray(DINO, np.float64)
E = np.array(EPS)
UE = sorted(set(EPS))
Y = {k: np.asarray(v) for k, v in TGT.items()}
N = len(E)
print("\n[wpl] %d masked NO_LABEL - windows n=%d - episodes %d - fmap %s"
      % (n_masked, N, len(UE), FMAP.shape), flush=True)


def pooled(grid):
    """Derive a grid from the ONE banked feature map -- never a second forward."""
    t = torch.from_numpy(FMAP)
    return torch.nn.functional.adaptive_avg_pool2d(t, grid).reshape(
        len(t), -1).numpy().astype(np.float64)


ARMS = {}
for g in ((2, 4), (8, 8)):
    ARMS["trunk %dx%d linear" % g] = (pooled(g), "linear")
    ARMS["trunk %dx%d rbf" % g] = (pooled(g), "rbf")
ARMS["dinov3 2x4 linear"] = (DINO, "linear")
for k, (X, kern) in ARMS.items():
    print("   %-22s d=%-6d %s  std %.4g  nonfinite %d"
          % (k, X.shape[1], kern, X.std(), int((~np.isfinite(X)).sum())), flush=True)
    if not np.isfinite(X).all():
        raise RuntimeError("arm %r has non-finite features; a poisoned arm scores "
                           "like a finding" % k)


def auc(s, y):
    p, n = y.sum(), (1 - y).sum()
    if p == 0 or n == 0:
        return float("nan")
    o = np.argsort(s, kind="mergesort")
    r = np.empty(len(s), float)
    r[o] = np.arange(1, len(s) + 1, dtype=float)
    ss = s[o]
    i = 0
    while i < len(ss):
        j = i
        while j + 1 < len(ss) and ss[j + 1] == ss[i]:
            j += 1
        if j > i:
            r[o[i:j + 1]] = r[o[i:j + 1]].mean()
        i = j + 1
    return float((r[y == 1].sum() - p * (p + 1) / 2) / (p * n))


LAMBDAS = (1e-1, 1.0, 10.0, 1e2, 1e3, 1e4, 1e5, 1e6)
GAMMAS = (0.25, 1.0, 4.0)          # x 1/d ; swept INSIDE the fold, never on the score split


def _sq(A, B):
    return (np.einsum("ij,ij->i", A, A)[:, None] + np.einsum("ij,ij->i", B, B)[None, :]
            - 2.0 * (A @ B.T))


class FoldCache:
    """LOEO dual ridge; `kern` selects a linear or RBF Gram.

    The dual solve is indifferent to where the Gram came from, so the RBF arm
    reuses the exact folds, lambda sweep, calibration and permutation machinery
    the linear arms use -- no second estimator to validate.
    """

    def __init__(self, F, kern):
        self.folds = []
        for ep in UE:
            te = E == ep
            A, B = F[~te], F[te]
            mu, sd = A.mean(0), A.std(0) + 1e-8
            A, B = (A - mu) / sd, (B - mu) / sd
            inner = np.arange(len(A)) % 4 != 0
            gammas = [None] if kern == "linear" else [g / A.shape[1] for g in GAMMAS]
            # ⭐ THE SQUARED-DISTANCE MATRICES DO NOT DEPEND ON GAMMA. Computing
            # them inside the gamma loop repeated an O(n^2 d) product three times
            # per fold -- at d=45,056 that is ~90 s wasted per fold, i.e. hours
            # across the panel. Hoisted: the gamma sweep is now three cheap
            # elementwise exponentials over matrices computed once.
            if kern == "linear":
                sqA = sqB = sqXi = sqGi = None
            else:
                sqA, sqB = _sq(A, A), _sq(B, A)
                sqXi, sqGi = _sq(A[~inner], A[inner]), _sq(A[inner], A[inner])
            per = []
            for gm in gammas:
                if gm is None:
                    G, BA = A @ A.T, B @ A.T
                    Xi, Gi = A[~inner] @ A[inner].T, A[inner] @ A[inner].T
                else:
                    G, BA = np.exp(-gm * sqA), np.exp(-gm * sqB)
                    Xi, Gi = np.exp(-gm * sqXi), np.exp(-gm * sqGi)
                ev, Q = np.linalg.eigh(G)
                ev2, Q2 = np.linalg.eigh(Gi)
                per.append({"ev": ev, "Q": Q, "BAQ": BA @ Q, "ev2": ev2, "Q2": Q2,
                            "XinQ2": Xi @ Q2})
            self.folds.append({"te": te, "tr": ~te, "inner": inner, "per": per})

    def scores(self, y):
        out = np.zeros(len(y))
        for f in self.folds:
            ytr = y[f["tr"]]
            yi, yo = ytr[f["inner"]], ytr[~f["inner"]]
            # ⛔ A DEFAULT THAT IS ALWAYS VALID. If every (gamma, lambda) pair
            # scores NaN -- which happens whenever the fold's inner validation
            # split happens to contain no positives -- a `(-inf, None, None)`
            # seed leaves `c` as None and the solve dies with a TypeError. Worse
            # than dying would be silently skipping the fold, so the seed is the
            # most-regularised candidate: a defined, maximally conservative
            # choice rather than an absent one.
            best = (-np.inf, f["per"][0], LAMBDAS[-1])
            for c in f["per"]:
                Q2ty = c["Q2"].T @ yi
                for lam in LAMBDAS:
                    a = auc(c["XinQ2"] @ (Q2ty / (c["ev2"] + lam)), yo)
                    if a == a and a > best[0]:
                        best = (a, c, lam)
            _, c, lam = best
            ah = (c["Q"].T @ ytr) / (c["ev"] + lam)
            s_tr = c["Q"] @ (c["ev"] * ah)
            out[f["te"]] = (c["BAQ"] @ ah - s_tr.mean()) / (s_tr.std() + 1e-12)
        return out


def perm(y, kind, r):
    z = y.copy()
    if kind == "global":
        r.shuffle(z)
        return z
    for ep in UE:
        m = E == ep
        v = z[m]
        r.shuffle(v)
        z[m] = v
    return z


t1 = time.time()
res = {n: {"base_rate": float(y.mean()), "n_pos": int(y.sum()), "arms": {}}
       for n, y in Y.items()}
for name, (X, kern) in ARMS.items():
    C = FoldCache(X, kern)
    print("[wpl] cache %-22s built (%.0f s)" % (name, time.time() - t1), flush=True)
    for tname, y in Y.items():
        obs = auc(C.scores(y), y)
        nulls = {}
        for kind in ("global", "within"):
            r = np.random.default_rng(abs(hash((name, tname, kind))) % (2 ** 31))
            v = [auc(C.scores(perm(y, kind, r)), y) for _ in range(N_PERM)]
            v = np.array([x for x in v if x == x])
            nulls[kind] = ({"mean": float("nan"), "p": float("nan"), "n": 0}
                           if not len(v) else
                           {"mean": float(v.mean()), "p": float((v >= obs).mean()),
                            "n": int(len(v))})
        res[tname]["arms"][name] = {"auc": obs, "null": nulls,
                                    "adj": obs - nulls["within"]["mean"]}
        print("   %-22s %-24s auc %.4f  adj %+.4f  p_glob %.3f  p_within %.3f (%.0f s)"
              % (name, tname, obs, obs - nulls["within"]["mean"],
                 nulls["global"]["p"], nulls["within"]["p"], time.time() - t1),
              flush=True)
    del C

const = FoldCache(np.ones((N, 1)), "linear")
y0 = Y["vru<60m IN-FOV"]
a_const = auc(const.scores(y0), y0)
print("\n  CONSTANT-only control  %.4f   <- must be 0.5000 EXACTLY" % a_const)
pct = {a: res["PC-TRUNK sel lateral>0"]["arms"][a]["auc"] for a in ARMS}
print("  PC-TRUNK per arm (every TRUNK arm must win decisively):")
for a in ARMS:
    print("      %-22s %.4f" % (a, pct[a]))
trunk_ok = all(v > 0.75 for k, v in pct.items() if k.startswith("trunk"))
print("  trunk arms readable: %s" % ("YES" if trunk_ok else "NO -- panel unreadable"))

print("\n%-24s%s" % ("VERDICT on the near band", ""))
base = res["vru<20m IN-FOV"]["arms"]["trunk 2x4 linear"]
for a in ARMS:
    r = res["vru<20m IN-FOV"]["arms"][a]
    print("   %-22s adj %+.4f  p_within %.3f   (baseline adj %+.4f)"
          % (a, r["adj"], r["null"]["within"]["p"], base["adj"]))
# ⛔ THE VERDICT MUST BE PER TARGET. Version 1 computed `rescued` on
# `vru<20m IN-FOV` ALONE and printed a single global sentence -- so it announced
# "NOT RESCUED" while the FAR band's two RBF arms were clearing at p 0.040 and
# 0.020. A verdict that aggregates over targets hides exactly the structure the
# panel was built to expose, and it is the same family as pooling a consistency
# score over metric families: the interesting answer lives in the split.
rescued = {t: [a for a in ARMS if a.startswith("trunk")
               and res[t]["arms"][a]["null"]["within"]["p"] < 0.05]
           for t in ("vru<20m IN-FOV", "vru<60m IN-FOV")}
if abs(a_const - 0.5) > 1e-9 or not trunk_ok:
    verdict = "CONTROLS FAILED"
else:
    parts = []
    for t, arms in rescued.items():
        parts.append("%s: %s" % (t, "RESCUED by " + ", ".join(arms) if arms
                                 else "NOT rescued by any trunk arm"))
    verdict = " | ".join(parts)
# ⚠️ MULTIPLICITY, stated with the verdict rather than left to the reader: this
# panel runs 5 arms x 2 VRU targets = 10 tests at alpha 0.05, so ~0.5 false
# positives are expected by construction, and with 200 permutations the p-value
# resolution is 0.005. A single p just under 0.05 is a lead, not a result.
verdict += "  [10 tests at alpha .05; ~0.5 expected false positives; p resolution 0.005]"
print("\n  => %s" % verdict)
json.dump({"n": N, "episodes": len(UE), "n_perm": N_PERM, "n_masked": n_masked,
           "arms": {k: {"d": int(v[0].shape[1]), "kernel": v[1]} for k, v in ARMS.items()},
           "results": res, "constant_control": a_const, "pc_trunk": pct,
           "trunk_arms_readable": bool(trunk_ok), "rescued_by_target": rescued,
           "verdict": verdict, "_join": JOIN,
           "_tier": "T0; NON-PARITY pilot; LOEO; permutation null (global + "
                    "within-episode); gamma and lambda fitted inside the fold only"},
          _io.open(O + "/wpl_trunk_pooling_kernel.json", "w", encoding="utf-8"), indent=1)
print("\n-> wpl_trunk_pooling_kernel.json")
