"""Render every table in TEMPORAL_HYPOTHESIS.md straight from the result JSONs.

No number in the report is typed by hand. The B4 stream adopted this after a
cross-stream numeric transplant put "2,049 vs 2.17 M" into a document about two
arms that were really 129 and 417,028 (RETRACTION_LOG R-2026-08-03-h); a table
that is generated cannot drift from the artifact it claims to summarise.

usage:
  python render_tables.py --results results_temporal.json \
      --subspace results_subspace.json --out tables.md
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

SITS = ("lane_change", "roundabout", "intersection")
GROUPS = [
    ("A. WINDOW at MATCHED capacity (flat 128 -> 129 params/head everywhere)",
     ["ridge_app128_w1", "ridge_app64_w2", "ridge_app32_w4", "ridge_app16_w8",
      "ridge_app8_w16", "ridge_app4_w32"]),
    ("B. WINDOW at FIXED rank 16 (capacity allowed to grow with the window)",
     ["ridge_app16_w1", "ridge_app16_w4", "ridge_app16_w8", "ridge_app16_w16",
      "ridge_app16_w32"]),
    ("C. MOTION SUBSPACE (PCA fitted on the temporal difference)",
     ["ridge_mot16_w8", "ridge_app8mot8_w8", "ridge_app16mot16_w8", "ridge_mot16_w32"]),
    ("D. the DEPLOYED TRANSFORMER budget",
     ["tf_app16_w8_d128", "tf_app16_w32", "tf_app8mot8_w8", "tf_app16_w8_diffparam"]),
    ("CONTROLS (not deployable arms)",
     ["ridge_app16_w8_diffparam", "CPOS_ego_w8", "CPOS_ego_w32",
      "CPOS_ORACLE_egofuture30"]),
]


def f(x, n=4):
    return "-" if x is None else (f"{x:.{n}f}" if isinstance(x, (int, float)) else str(x))


def ci(d, n=3):
    if d is None:
        return "REFERENCE"
    star = " **SEP**" if d.get("separated") else ""
    return f"{d['delta']:+.{n}f} [{d['lo']:+.{n}f}, {d['hi']:+.{n}f}]{star}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default="results_fast.json",
                    help="the LADDER (results_fast.json — bit-identical to the slow run)")
    ap.add_argument("--controls", default="results_temporal.json",
                    help="the run that carries the NEG_* and invariance control blocks")
    ap.add_argument("--families", default="results_four_families.json")
    ap.add_argument("--subspace", default="results_subspace.json")
    ap.add_argument("--horizon", default="results_horizon.json")
    ap.add_argument("--stillframe", default="results_stillframe.json")
    ap.add_argument("--out", default="tables.md")
    a = ap.parse_args()
    R = json.loads(Path(a.results).read_text(encoding="utf-8"))
    S = json.loads(Path(a.subspace).read_text(encoding="utf-8"))
    C = json.loads(Path(a.controls).read_text(encoding="utf-8"))
    R.setdefault("controls", C.get("controls", {}))
    if Path(a.families).exists():
        FF = json.loads(Path(a.families).read_text(encoding="utf-8"))
        R["four_families"] = {s: v for s, v in FF["situations"].items()}
    ref = R.get("reference_arm") or R["protocol"]["reference_arm"]
    L = []

    L.append("<!-- GENERATED BY render_tables.py — DO NOT EDIT BY HAND -->\n")

    # ---- power ------------------------------------------------------------
    L.append("## T0. Power, counted before any score was read (C-POW bar = 40 clusters)\n")
    L.append("| situation | rows scorable | positives | **positive CLUSTERS** | base rate | C-POW |")
    L.append("|---|---:|---:|---:|---:|---|")
    for s in SITS:
        r = R["per_situation"][s]
        n = r["n_clusters_with_a_positive"]
        L.append(f"| `{s}` | {r['n_scorable']:,} | {r['n_pos']:,} | **{n}** | "
                 f"{r['base_rate']:.5f} | {'PASS' if n >= 40 else '**UNDERPOWERED**'} |")

    # ---- the subspace diagnostic -----------------------------------------
    L.append("\n## T1. H-T2 mechanism — does appearance PCA discard the motion subspace?\n")
    L.append("Variance is always measured **about the own mean of the matrix being measured**. "
             "`results_subspace.json`.\n")
    L.append("| Δ lag | rank | Δ-variance kept by the **appearance** basis | "
             "by the **motion** basis | motion advantage | mean principal cos |")
    L.append("|---|---:|---:|---:|---:|---:|")
    for k, row in S["ranks"].items():
        L.append(f"| {row['delta_lag_s']} s | {k.split('rank')[1]} | "
                 f"{row['DELTA_var_in_APPEARANCE_basis']:.4f} | "
                 f"{row['DELTA_var_in_MOTION_basis']:.4f} | "
                 f"**{row['delta_variance_LOST_by_using_the_appearance_basis']:+.4f}** | "
                 f"{row['mean_principal_cosine']:.4f} |")

    # ---- the ladder -------------------------------------------------------
    for s in SITS:
        r = R["per_situation"][s]
        L.append(f"\n## T2.{SITS.index(s)+1} `{s}` — the ladder "
                 f"({r['n_pos']:,} positives in {r['n_clusters_with_a_positive']} clusters, "
                 f"base {r['base_rate']:.5f})\n")
        L.append(f"**VERDICT: {r['VERDICT']}** — {r['_verdict_note']}\n")
        L.append("| arm | history | flat | params | AP | AP-lift [95 %] | "
                 "P@5 % | R@5 % | fires / true | vs own null | "
                 f"vs `{ref}` |")
        L.append("|---|---:|---:|---:|---:|---|---:|---:|---:|---|---|")
        for title, arms in GROUPS:
            L.append(f"| *{title}* | | | | | | | | | | |")
            for n in arms:
                if n not in r["arms"]:
                    continue
                q = r["arms"][n]
                op = q["op_5pct"]
                mark = " ⬅ REF" if n == ref else ""
                L.append(
                    f"| `{n}`{mark} | {q['history_s']} s | {q['flat_dim']} | "
                    f"{q['params_per_head']:,} | {q['ap']:.5f} | "
                    f"{q['point']:.3f} [{q['lo']:.3f}, {q['hi']:.3f}] | "
                    f"{f(op['precision'])} | {f(op['recall'])} | "
                    f"{op['n_alarm']:,} / {op['n_pos']:,} | "
                    f"{ci(q['paired_vs_own_null'])} | {ci(q['paired_vs_reference'])} |")

    # ---- controls ---------------------------------------------------------
    L.append("\n## T3. Controls\n")
    L.append("### Parameterisation invariance — an exactly invertible remap of the reference\n")
    L.append("| situation | Δ AP-lift (diffparam − reference) |")
    L.append("|---|---|")
    for s in SITS:
        d = (R["controls"].get("PARAMETERISATION_INVARIANCE", {}).get(s, {})
             .get("delta_ap_lift"))
        if d is None:      # the ladder carries the same contrast per arm
            d = R["per_situation"][s]["arms"]["ridge_app16_w8_diffparam"]["paired_vs_reference"]
        L.append(f"| `{s}` | {ci(d, 4)} |")
    L.append("\n### NEG_LABEL — labels permuted across whole clusters (AP-lift, 1.0 = chance)\n")
    nl = R["controls"]["NEG_LABEL_ap_lift"]
    keys = sorted({k for v in nl.values() for k in v})
    L.append("| situation | " + " | ".join(f"`{k}`" for k in keys) + " |")
    L.append("|---|" + "---|" * len(keys))
    for s in SITS:
        L.append(f"| `{s}` | " + " | ".join(f(nl[s].get(k), 4) for k in keys) + " |")

    # ---- the four families ------------------------------------------------
    L.append("\n## T4. The four binding metric families (peak arm vs the reference)\n")
    for s in SITS:
        ff = R["four_families"][s]
        peak = R["per_situation"][s]["peak_arm"]
        L.append(f"\n### `{s}` — PEAK `{peak}` vs `{ref}`\n")
        t = ff["families"]["TACTICAL"]
        L.append(f"**TACTICAL** — {t['n_rows_scored']:,} rows, {t['n_pos']:,} positives, "
                 f"base {t['base_rate']:.5f}\n")
        L.append("| arm | AP | AP-lift | P@5 % | R@5 % | fires / true | median lead |")
        L.append("|---|---:|---:|---:|---:|---:|---:|")
        for nm in t["ap"]:
            op = t["operating_point_5pct"][nm]
            lead = t["anticipation_lead"][nm]["median_lead_s"]
            L.append(f"| `{nm}` | {t['ap'][nm]:.5f} | {t['ap_lift'][nm]:.3f} | "
                     f"{f(op['precision'])} | {f(op['recall'])} | "
                     f"{op['n_alarm']:,} / {op['n_pos']:,} | "
                     f"{'-' if lead is None else f'{lead} s'} |")
        L.append(f"\npaired Δ AP-lift: {ci(t['paired_delta_ap_lift'])}\n")
        for fam in ("LONGITUDINAL", "LATERAL"):
            b = ff["families"][fam]
            if b.get("_status") == "UNAVAILABLE":
                L.append(f"**{fam}** — UNAVAILABLE: {b['_reason']} (n = {b['n_rows']:,})\n")
                continue
            L.append(f"**{fam}** — decision quality stratified by regime. "
                     f"Not computable directly: {b['_not_computable']} "
                     f"({b['_not_computable_reason']}).\n")
            L.append("| stratum | rows | pos | base | peak lift | ref lift | paired Δ |")
            L.append("|---|---:|---:|---:|---:|---:|---|")
            for nm, st in b["strata"].items():
                if st.get("_status") == "UNPOWERED":
                    L.append(f"| {nm} | {st['n_rows']:,} | {st['n_pos']} | - | - | - | "
                             f"**UNPOWERED** |")
                    continue
                k = list(st["ap_lift"])
                L.append(f"| {nm} | {st['n_rows']:,} | {st['n_pos']} | "
                         f"{st['base_rate']:.5f} | {st['ap_lift'][k[0]]:.3f} | "
                         f"{st['ap_lift'][k[1]]:.3f} | {ci(st['paired_delta_ap_lift'])} |")
            L.append("")
        sg = ff["families"]["STRATEGIC"]
        L.append(f"**STRATEGIC** — {sg['_status']}: {sg['_reason']} (n = {sg['n_rows']:,})\n")

    # ---- the anticipation horizon -----------------------------------------
    if a.horizon and Path(a.horizon).exists():
        H = json.loads(Path(a.horizon).read_text(encoding="utf-8"))
        L.append("\n## T5. The anticipation HORIZON (reference recipe, `ridge_app16_w8`)\n")
        L.append("⚠️ **The row set and the base rate BOTH move with the lead** — a longer lead "
                 "creates more positive frames and masks more end-of-clip rows — so these rows "
                 "are *not* the identical-row comparison the ladder is. `precision_lift` "
                 "(P@5 % ÷ base rate) is the column that is comparable across leads; raw AP-lift "
                 "is not, because its ceiling is 1/base.\n")
        for s in SITS:
            rows = [(l, H["per_situation"][s].get(f"lead_{l}")) for l in H["leads_s"]]
            rows = [(l, r) for l, r in rows if r and "_status" not in r]
            if not rows:
                continue
            v = H.get("verdict", {}).get(s, {})
            L.append(f"\n### `{s}` — {v.get('VERDICT', '?')}\n")
            L.append("| lead | rows | pos | clusters+ | C-POW | base | AP | AP-lift [95 %] | "
                     "P@5 % | fires / true | **precision lift** | Δ vs null |")
            L.append("|---:|---:|---:|---:|---|---:|---:|---|---:|---:|---:|---|")
            for l, r in rows:
                op = r["op_5pct"]
                L.append(
                    f"| {l} s | {r['n_scorable']:,} | {r['n_pos']:,} | "
                    f"{r['n_clusters_with_a_positive']} | "
                    f"{'PASS' if r['C_POW_pass'] else '**FAIL**'} | {r['base_rate']:.5f} | "
                    f"{r['ap']:.5f} | {r['ap_lift']['point']:.3f} "
                    f"[{r['ap_lift']['lo']:.3f}, {r['ap_lift']['hi']:.3f}] | "
                    f"{f(op['precision'])} | {op['n_alarm']:,} / {op['n_pos']:,} | "
                    f"**{f(op['precision_lift'], 3)}** | {ci(r['paired_vs_null'])} |")

    # ---- the still-frame control ------------------------------------------
    if a.stillframe and Path(a.stillframe).exists():
        SF = json.loads(Path(a.stillframe).read_text(encoding="utf-8"))
        L.append("\n## T6. The STILL-FRAME control — is the classifier reading appearance?\n")
        L.append("Same encoder, same clips, same labels; the 9-channel input is the last RGB frame "
                 "replicated 3x, so it carries **zero** inter-frame motion. `recovery` = "
                 "(still_lift − still_null) ÷ (real_lift − real_null), i.e. skill over each "
                 "substrate's OWN permuted null. ⚠️ `recovery` is meaningless when the real skill "
                 "is ~0 — flagged rather than printed.\n")
        L.append("| situation | arm | real lift (null) | **real skill** | still lift (null) | "
                 "**still skill** | **recovery** | still − real |")
        L.append("|---|---|---:|---:|---:|---:|---:|---|")
        for s in SITS:
            row = SF["per_situation"].get(s)
            if not row:
                continue
            for arm, q in row["arms"].items():
                r_, s_ = q["real"], q["still"]
                rec = q["RECOVERY_FRACTION"]
                rec_s = ("**n/a** (real skill ≈ 0)" if rec is None or abs(r_["skill_over_null"]) < 0.05
                         else f"**{rec:.3f}**")
                L.append(
                    f"| `{s}` | `{arm}` | {r_['ap_lift']['point']:.3f} "
                    f"({r_['own_null_ap_lift']:.3f}) | {r_['skill_over_null']:+.3f} | "
                    f"{s_['ap_lift']['point']:.3f} ({s_['own_null_ap_lift']:.3f}) | "
                    f"{s_['skill_over_null']:+.3f} | {rec_s} | "
                    f"{ci(q['paired_still_minus_real'])} |")

    Path(a.out).write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {a.out}  ({len(L)} lines)")


if __name__ == "__main__":
    main()
