"""Collect every Research package's COMMS.md into one readable digest.

⛔ WHY THIS EXISTS. Each §3 work package writes a `COMMS.md` addressed to a reader --
"To the Master Mind", "To the Deployment line", "Owed back". MEASURED 2026-08-31:
**eight of them existed and not one had ever been routed to anybody.** The Lab was
writing letters and posting them into a drawer. A channel nobody is subscribed to is
not a channel, and the packages are the Lab's only outbound path.

⭐ WHAT MAKES THIS DIFFERENT FROM "READ THE PACKAGES". The digest surfaces the two
things a reader acts on -- the addressed lines and the OWED-BACK items -- in one file,
newest first, with the source path beside each so the full package is one click away.
Nobody opens eight COMMS files; everybody opens one digest.

⚠️ THIS FILE IS GENERATED. It carries a banner saying so, because a generated file that
looks hand-written invites hand-edits, and the next regeneration silently destroys them.
Same rule the campaign learned the hard way: generate + assert, never type.

⚠️ OUTPUT IS ASCII-ONLY on stdout. The dev box is cp1252 and a tool that dies printing
its own house glyphs fails for the wrong reason (MEASURED 2026-08-21). The DIGEST file
itself is written utf-8 and keeps the glyphs -- only the console output is constrained.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

LAB = "TanitAD Research Lab"
DIGEST = f"{LAB}/LAB_DIGEST.md"
#: Lines that name an obligation. Kept EXPLICIT rather than "any bold line" -- a
#: heuristic that over-matches trains readers to skim the digest, which is the exact
#: failure the digest exists to fix.
#: ⚠️ TWO FORMS, because the first version of this matcher MISSED A LIVE ESCALATION.
#: MEASURED: the Architecture package addressed the Master Mind and the PI with a
#: HEADING (`## ESCALATION TO THE MASTER MIND / PI`), not a bold lead-in, so the
#: bold-only pattern reported "no addressed line" on the one package that was
#: escalating a correction to a live gate document. A router that silently drops the
#: message it most needed to carry is worse than no router.
OWED = re.compile(r"^\*\*(owed back|to the|action|needed|blocked|decision)\b", re.I)
ADDR_HEADING = re.compile(
    r"^#{2,3}\s+.*\b(escalation|to the|action required|action requested|"
    r"owed|decision needed)\b", re.I)


def packages(root: Path) -> list[tuple[str, str, Path]]:
    """(field, slug, comms_path) for every Research package, newest slug first."""
    out: list[tuple[str, str, Path]] = []
    for c in sorted((root / LAB).glob("*/Research/*/COMMS.md")):
        slug = c.parent.name
        field = c.parent.parent.parent.name
        out.append((field, slug, c))
    out.sort(key=lambda r: r[1], reverse=True)
    return out


def parse(p: Path) -> tuple[str, list[str]]:
    """(title, owed-lines). Title from <title>, falling back to the first heading."""
    txt = p.read_text(encoding="utf-8", errors="replace")
    m = re.search(r"<title>(.*?)</title>", txt, re.S)
    title = m.group(1).strip() if m else ""
    if not title:
        h = re.search(r"^#\s+(.+)$", txt, re.M)
        title = h.group(1).strip() if h else p.parent.name
    owed: list[str] = []
    lines = txt.splitlines()
    for i, line in enumerate(lines):
        ln = line.strip()
        is_heading = bool(ADDR_HEADING.match(ln))
        if not (OWED.match(ln) or is_heading):
            continue
        body = ln.lstrip("#").strip() if is_heading else ln
        for nxt in lines[i + 1:i + 5]:
            t = nxt.strip()
            if not t or t.startswith("#") or t.startswith("|"):
                break
            if t.startswith("**") and not is_heading:
                break
            body += " " + t.lstrip("> ")
        owed.append(re.sub(r"\s+", " ", body)[:400])
    return title, owed


def render(root: Path) -> str:
    pk = packages(root)
    n_owed = sum(len(parse(c)[1]) for _, _, c in pk)
    out = [
        "<title>LAB_DIGEST - every package's COMMS, in one place</title>",
        "",
        "# LAB_DIGEST",
        "",
        "> GENERATED by `stack/scripts/lab_digest.py`. DO NOT HAND-EDIT -- the next",
        "> regeneration overwrites it. Edit the source `COMMS.md` in the package instead.",
        "",
        "⛔ **Why this file exists.** Every §3 package writes a `COMMS.md` addressed to a",
        "reader. MEASURED 2026-08-31: **eight existed and none had ever been routed.** The",
        "Lab was writing letters into a drawer. This is the drawer, opened.",
        "",
        f"**{len(pk)} packages · {n_owed} addressed/owed items · newest first.**",
        "",
        "---",
        "",
    ]
    for field, slug, c in pk:
        title, owed = parse(c)
        out.append(f"## {slug} — {field}")
        out.append("")
        if title:
            out.append(f"*{title}*")
            out.append("")
        if owed:
            for o in owed:
                out.append(f"- {o}")
        else:
            out.append("- *(no addressed line — the package speaks only to the record)*")
        out.append("")
        rel = c.parent.relative_to(root).as_posix()
        out.append(f"`{rel}/`")
        out.append("")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--repo", default=".")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the digest is stale, do not write")
    a = ap.parse_args()
    root = Path(a.repo).resolve()
    new = render(root)
    dst = root / DIGEST
    old = dst.read_text(encoding="utf-8") if dst.exists() else ""

    if a.check:
        if old == new:
            print("[digest] OK - up to date.")
            return 0
        print("[digest] STALE - regenerate with: python stack/scripts/lab_digest.py")
        return 1
    if old == new:
        print(f"[digest] unchanged ({len(packages(root))} packages).")
        return 0
    dst.write_text(new, encoding="utf-8")
    print(f"[digest] wrote {DIGEST} - {len(packages(root))} packages.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
