"""RESOLUTION-GAIN — render `res_result.json` into the markdown tables the report quotes.

Every number in `RESOLUTION_GAIN.md` comes out of this script, so nothing is transcribed by hand.

usage:  python res_tables.py <res_result.json> <out_md>
"""
from __future__ import annotations

import json
import sys

LADDER_A = ["V5_640", "D_today", "D_1p5", "D_2", "D_3", "D_6"]
LADDER_B = ["B_today", "B_D2", "B_D6"]
PXDEG = {"V5_640": 5.3333, "D_today": 4.6426, "D_1p5": 3.5556, "D_2": 2.6667,
         "D_3": 1.7778, "D_6": 0.8889, "A_1p5_alias": 3.5556,
         "B_today": 4.6426, "B_D2": 2.3213, "B_D6": 0.7738, "U_960": 8.0000}


def ci(d, n=4):
    if d is None:
        return "—"
    star = " **sep**" if d["separated"] else ""
    return f"{d['delta']:+.{n}f} [{d['lo']:+.{n}f}, {d['hi']:+.{n}f}]{star}"


def main():
    src, out = sys.argv[1:3]
    R = json.load(open(src))
    L = []
    a = L.append
    a(f"*Generated by `res_tables.py` from `{src.split(chr(92))[-1].split('/')[-1]}` — "
      f"{R['n_clips']} clips, {R['n_rows']} rows, B = {R['n_boot']}, "
      f"estimator: {R['estimator']}.*\n")

    # ---------------- P1 power ----------------
    a("## P1 — power (the registered guard: 40 held-out positive clip clusters)\n")
    a("| situation | held-out rows | held-out positives | **positive clip clusters** | base rate | C-POW |")
    a("|---|---:|---:|---:|---:|---|")
    for s, p in R["P1"]["power"].items():
        a(f"| {s} | {p['n_heldout_rows']:,} | {p['n_heldout_pos']:,} | "
          f"**{p['n_positive_clip_clusters']}** | {p['base_rate']:.5f} | {p['C_POW']} |")
    a("")

    # ---------------- P1 controls ----------------
    a("## P1 — controls (C-NEG must land at chance; the chance comparator is audited)\n")
    a("| situation | C-NEG shuffled AP | base rate | AP/base | separated above chance? |")
    a("|---|---:|---:|---:|---|")
    for s, c in R["P1"].get("controls", {}).items():
        n = c["C_NEG_shuffled"]
        a(f"| {s} | {n['AP']:.5f} | {n['base_rate']:.5f} | {n['AP_over_base']:.3f} | "
          f"{'⛔ LEAK' if n['above_chance'] else '✅ at chance'} |")
    a("")

    # ---------------- P1 per-arm + contrasts ----------------
    for s in R["P1"]["arms"]:
        if not R["P1"]["arms"][s]:
            continue
        a(f"## P1 — {s}: the ladder\n")
        a("| arm | px/deg | AP | 95 % CI | AP/chance | **Δ vs V5_640 [95 % CI]** |")
        a("|---|---:|---:|---|---:|---|")
        for arm in LADDER_A + ["A_1p5_alias", "U_960"] + LADDER_B:
            v = R["P1"]["arms"][s].get(arm)
            if v is None:
                continue
            d = R["P1"]["contrasts"][s].get(f"{arm}_vs_V5_640")
            a(f"| `{arm}` | {PXDEG.get(arm, float('nan')):.4f} | {v['AP']:.5f} | "
              f"[{v['lo']:.5f}, {v['hi']:.5f}] | {v['AP_over_base']:.3f} | {ci(d)} |")
        a("")
        a("**Ladder B against its own baseline `B_today`:**\n")
        a("| arm | px/deg | AP | **Δ vs B_today [95 % CI]** |")
        a("|---|---:|---:|---|")
        for arm in LADDER_B[1:]:
            v = R["P1"]["arms"][s].get(arm)
            if v is None:
                continue
            d = R["P1"]["contrasts"][s].get(f"{arm}_vs_B_today")
            a(f"| `{arm}` | {PXDEG[arm]:.4f} | {v['AP']:.5f} | {ci(d)} |")
        a("")
        vd = R["P1"]["verdicts"][s]
        a(f"**VERDICT ({s}): `{vd['verdict']}`** — {vd['why']}"
          + (f" (DR = {vd['DR']})" if "DR" in vd else "") + "\n")

    # ---------------- P2 ----------------
    for t in R["P2"]["arms"]:
        if not R["P2"]["arms"][t]:
            continue
        c = R["P2"]["controls"][t]["C_NEG_shuffled_R2"]
        a(f"## P2 — image-only ridge on **{t}** (out-of-sample R², C-NEG shuffled R² = {c:.5f})\n")
        a("| arm | px/deg | R² | 95 % CI | **ΔR² vs V5_640 [95 % CI]** |")
        a("|---|---:|---:|---|---|")
        for arm in LADDER_A + ["A_1p5_alias", "U_960"] + LADDER_B:
            v = R["P2"]["arms"][t].get(arm)
            if v is None:
                continue
            d = R["P2"]["contrasts"][t].get(f"{arm}_vs_V5_640")
            a(f"| `{arm}` | {PXDEG.get(arm, float('nan')):.4f} | {v['R2']:.5f} | "
              f"[{v['lo']:.5f}, {v['hi']:.5f}] | {ci(d)} |")
        a("")
        a("**Ladder B against its own baseline `B_today`:**\n")
        a("| arm | px/deg | R² | **ΔR² vs B_today [95 % CI]** |")
        a("|---|---:|---:|---|")
        for arm in LADDER_B[1:]:
            v = R["P2"]["arms"][t].get(arm)
            if v is None:
                continue
            d = R["P2"]["contrasts"][t].get(f"{arm}_vs_B_today")
            a(f"| `{arm}` | {PXDEG[arm]:.4f} | {v['R2']:.5f} | {ci(d)} |")
        a("")
        vd = R["P2"]["verdicts"][t]
        a(f"**VERDICT ({t}): `{vd['verdict']}`** — {vd['why']}"
          + (f" (DR = {vd['DR']})" if "DR" in vd else "") + "\n")

    # ---------------- P3 — the SAME heads, per situation (amendment A1) ----------------
    for key in R.get("P3", {}).get("arms", {}):
        p = R["P3"]["power"][key]
        a(f"## P3 — `{key}` (per-situation slice of the P2 head; "
          f"{p['n_heldout_rows']:,} held-out rows, {p['n_positive_clip_clusters']} clip clusters, "
          f"C-POW {p['C_POW']})\n")
        a("| arm | px/deg | R² | **ΔR² vs V5_640 [95 % CI]** |")
        a("|---|---:|---:|---|")
        for arm in LADDER_A + ["A_1p5_alias", "U_960"] + LADDER_B:
            v = R["P3"]["arms"][key].get(arm)
            if v is None:
                continue
            d = R["P3"]["contrasts"][key].get(f"{arm}_vs_V5_640")
            a(f"| `{arm}` | {PXDEG.get(arm, float('nan')):.4f} | {v['R2']:.5f} | {ci(d)} |")
        a("")
        a("**Ladder B against its own baseline `B_today`:**\n")
        a("| arm | px/deg | R² | **ΔR² vs B_today [95 % CI]** |")
        a("|---|---:|---:|---|")
        for arm in LADDER_B[1:]:
            v = R["P3"]["arms"][key].get(arm)
            if v is None:
                continue
            d = R["P3"]["contrasts"][key].get(f"{arm}_vs_B_today")
            a(f"| `{arm}` | {PXDEG[arm]:.4f} | {v['R2']:.5f} | {ci(d)} |")
        a("")
        vd = R["P3"]["verdicts"][key]
        a(f"**VERDICT ({key}): `{vd['verdict']}`** — {vd['why']}"
          + (f" (DR = {vd['DR']})" if "DR" in vd else "") + "\n")

    open(out, "w", encoding="utf-8").write("\n".join(L))
    print("\n".join(L))


if __name__ == "__main__":
    main()
