#!/usr/bin/env python3
"""Regenerate EVERY table in ``PSS_TWOSIDED.md`` from the artifacts.

The tables are generated, not hand-typed, so a number in the prose cannot drift
from the JSON it came from. Also measures the ``comfort`` means that justify
REFUSING the per-arm gate — MEASURED here rather than inherited from the source
report, because that refusal is a load-bearing choice.

    python3 tables.py > ../artifacts/tables.md
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import torch

_HERE = Path(__file__).resolve()
_ART = _HERE.parents[1] / "artifacts"
_REPO = _HERE.parents[6]
for p in (str(_REPO / "stack"), str(_REPO / "taniteval")):
    if Path(p).is_dir() and p not in sys.path:
        sys.path.insert(0, p)
from taniteval import pseudosim as PS   # noqa: E402

D = json.loads((_ART / "panel_both_terms.json").read_text(encoding="utf-8"))
PROBES = set(D["probes_excluded"])
TERMS = ["clamp_v1", "twosided_asym_w0p5", "twosided_v2",
         "twosided_asym_w1p5", "twosided_asym_w2", "twosided_asym_w3"]


def ci(term, arm):
    c = (D["terms"][term]["composite_ci"] or {}).get(arm)
    return None if not c else c


def fmt_ci(c):
    return "—" if not c else f"{c['mean']:.4f} [{c['lo']:.4f}, {c['hi']:.4f}]"


def fmt_d(b):
    if not b or "PSS" not in b:
        return "—"
    x = b["PSS"]
    return (f"{x['delta']:+.4f} [{x['lo']:+.4f}, {x['hi']:+.4f}] "
            f"{'**SEP**' if x['separated'] else 'n.s.'}")


print("<!-- GENERATED by scripts/tables.py — do not hand-edit -->\n")

# ---------------------------------------------------------------- T1 ------- #
print("## T1 — the arm panel under BOTH terms, side by side\n")
print("| rank@v2 | arm | `PSS@clamp_v1` (PUBLISHED) | `PSS@twosided_v2` (NEW) "
      "| Δ | rank@v1 | `ego_progress` v1 → v2 |")
print("|--:|---|---|---|--:|--:|---|")
rank1 = {r["arm"]: r["rank"] for r in D["terms"]["clamp_v1"]["ranking"]}
for r in D["terms"]["twosided_v2"]["ranking"]:
    a = r["arm"]
    c1, c2 = ci("clamp_v1", a), ci("twosided_v2", a)
    e1 = D["terms"]["clamp_v1"]["ego_progress_mean"][a]
    e2 = D["terms"]["twosided_v2"]["ego_progress_mean"][a]
    d = (c2["mean"] - c1["mean"]) if (c1 and c2) else float("nan")
    mv = rank1.get(a, 0) - r["rank"]
    arrow = "" if mv == 0 else (f" ⬆{mv}" if mv > 0 else f" ⬇{-mv}")
    print(f"| {r['rank']}{arrow} | `{a}` | {fmt_ci(c1)} | {fmt_ci(c2)} | "
          f"{d:+.4f} | {rank1.get(a, '—')} | {e1:.4f} → {e2:.4f} |")
print()

# ---------------------------------------------------------------- T2 ------- #
print("## T2 — the pre-registered contrasts, both terms "
      "(paired episode-cluster bootstrap, B=2000, unit = val episode)\n")
print("| contrast | Δ`PSS@clamp_v1` (PUBLISHED) | Δ`PSS@twosided_v2` (NEW) |")
print("|---|---|---|")
order = ["v1_ego_v0__minus__v1_tactical_follow",
         "v1_ego_v0__minus__v1_tactical_oracle",
         "v1_ego_v0__minus__cv_holdv0",
         "v1_ego_oracle_lon__minus__cv_holdv0",
         "v1_ego_oracle_lon__minus__v1_tactical_follow",
         "refc_xl_v0on__minus__refc_xl_v0off",
         "refc_base_v0on__minus__refc_base_v0off",
         "v1_tactical_follow__minus__cv_holdv0",
         "nospeed_tactical_oracle__minus__cv_holdv0",
         "refc_xl_produced__minus__cv_holdv0",
         "refc_base_produced__minus__cv_holdv0",
         "v4_oracle__minus__cv_holdv0",
         "v1_lat_straight__minus__v1_tactical_follow",
         "v4_oracle__minus__v4_blind",
         "v1_ego_half__minus__v1_tactical_follow"]
for k in order:
    a, b = k.split("__minus__")
    print(f"| `{a}` − `{b}` | {fmt_d(D['paired']['clamp_v1'].get(k))} | "
          f"{fmt_d(D['paired']['twosided_v2'].get(k))} |")
print()

# ---------------------------------------------------------------- T3 ------- #
print("## T3 — RANKING SENSITIVITY to the over-travel slope `w`\n")
print("`under = max(1-r,0)`, `over = max(r-1,0)`, "
      "`score = clamp(clamp_v1(r) - w·over, 0, 1)`. "
      "`w = 1` is `twosided_v2`; `clamp_v1` is `w = 0`.\n")
hdr = "| arm | " + " | ".join(
    ("`clamp_v1` (w=0)" if t == "clamp_v1" else
     "`twosided_v2` (w=1)" if t == "twosided_v2" else
     "w=" + t.split("_w")[-1].replace("p", ".")) for t in TERMS) + " |"
print(hdr)
print("|---|" + "---|" * len(TERMS))
for r in D["terms"]["twosided_v2"]["ranking"]:
    a = r["arm"]
    cells = []
    for t in TERMS:
        rk = [x for x in D["terms"][t]["ranking"] if x["arm"] == a]
        cells.append(f"#{rk[0]['rank']} {rk[0]['PSS']:.4f}" if rk else "—")
    print(f"| `{a}` | " + " | ".join(cells) + " |")
real1 = {t: D["terms"][t]["rank1"] for t in TERMS}
# the top REALISABLE arm — rank 1 overall is an ORACLE under every term
oracle = {"v1_ego_oracle_lon", "oracle_lon_straight"}
real_top = {t: next(r["arm"] for r in D["terms"][t]["ranking"]
                    if r["arm"] not in oracle) for t in TERMS}
print(f"**rank 1 overall**, every term: `{sorted(set(real1.values()))}` "
      f"(⚠️ ORACLE — reads the ego's own logged future).  \n"
      f"**rank 1 among REALISABLE arms**, every term: "
      f"`{sorted(set(real_top.values()))}`.\n")

# ---------------------------------------------------------------- T4 ------- #
print("## T4 — the axis this lives on (term-independent, from the same dumps)\n")
print("| arm | along err mean | along \\|err\\| | along RMS | cross \\|err\\| | "
      "longitudinal share of sq. err | ratio <0.95 | ±5 % | >1.05 | p95 ratio |")
print("|---|--:|--:|--:|--:|--:|--:|--:|--:|--:|")
for r in D["terms"]["twosided_v2"]["ranking"]:
    a = r["arm"]
    d, q = D["decomposition"][a], D["ratio"][a]
    print(f"| `{a}` | {d['along_err_mean_m']:+.3f} | "
          f"{d['along_abs_err_mean_m']:.3f} | {d['along_rms_m']:.3f} | "
          f"{d['cross_abs_err_mean_m']:.3f} | "
          f"{d['longitudinal_share_of_sq_err']:.1%} | "
          f"{q['frac_under_0p95']:.2%} | {q['frac_within_5pct']:.2%} | "
          f"{q['frac_over_1p05']:.2%} | {q['p95']:.3f} |")
print()

# ---------------------------------------------------------------- T5 ------- #
print("## T5 — the PROBES: what the two terms do to a plan that goes TOO FAR\n")
print("| probe | what it is | `ego_progress`@v1 | admissible@v1 | "
      "`ego_progress`@v2 | admissible@v2 | `PSS@v2` |")
print("|---|---|--:|---|--:|---|--:|")
_desc = {"v1_ego_double": "v1's curve at **2× speed** (1.97× the logged distance)",
         "oracle_lon_straight": "straight plan walked to the **TRUE** distance",
         "v1_ego_half": "v1's curve at **half** speed (the degradation guard)",
         "stand_still": "the published adversary — does not move"}
for p in ("v1_ego_double", "oracle_lon_straight", "v1_ego_half", "stand_still"):
    if p not in D["terms"]["clamp_v1"]["ego_progress_mean"]:
        continue
    row = []
    for t in ("clamp_v1", "twosided_v2"):
        n = D["terms"][t]
        row += [n["ego_progress_mean"][p],
                "✅" if n["per_arm_range"][p]["ego_progress"]
                else "⛔ **INADMISSIBLE**"]
    c = ci("twosided_v2", p)
    pss = f"{c['mean']:.4f}" if c else "**REFUSED**"
    print(f"| `{p}` | {_desc.get(p, '')} | {row[0]:.4f} | {row[1]} | "
          f"{row[2]:.4f} | {row[3]} | {pss} |")
print()

# ---------------------------------------------------------------- T6 ------- #
print("## T6 — why the PER-ARM gate is REFUSED (MEASURED here, not inherited)\n")


def load_pw(path):
    z = np.load(path, allow_pickle=False)
    return {k: torch.as_tensor(z[k]) for k in
            ("traj", "ref_path", "ref_yaw", "v0", "pt_dlat", "pt_dyaw",
             "pt_dlon")} | {"eid": [str(x) for x in z["eid"]]}


print("| arm | `comfort` mean | per-arm-gate verdict |")
print("|---|--:|---|")
for a in ("v1_tactical_follow", "v1_ego_v0", "v1_ego_oracle_lon",
          "v1_lat_straight", "cv_holdv0", "v4_oracle", "refc_xl_produced"):
    src = D["arm_sources"].get(a)
    if not src:
        continue
    c = PS.score_windows(load_pw(src))["comfort"]
    adm = D["terms"]["twosided_v2"]["per_arm_range"][a]["comfort"]
    print(f"| `{a}` | {float(np.nanmean(c)):.4f} | "
          f"{'admissible' if adm else 'inadmissible'} |")
print("\n⛔ Re-timing a plan at constant speed **smooths** it, so `comfort` "
      "jumps by orders of magnitude between two arms that differ only in "
      "SCHEDULE. Under the per-arm gate that term enters the composite and "
      "turns the source stream's own primary from n.s. into SEPARATED — a "
      "verdict flip driven by a smoothing artefact, not by planning. The "
      "panel-wide gate drops `comfort` for every arm and is used throughout.\n")
