#!/usr/bin/env python3
"""Regenerate every table in TACTICAL_ACTION_INPUT.md FROM THE ARTIFACTS.

The panel's own rule, kept: tables are generated from the JSON, not hand-typed,
so a reviewer can diff the report against the data instead of trusting a
transcription. Writes ``artifacts/tables.md``.

    python3 summarize.py --panel artifacts/blockB_panel.json \
        --decomp artifacts/decomposition.json --out artifacts/tables.md
"""
from __future__ import annotations

import argparse
import io
import json
from pathlib import Path

ORDER = ["v1_ego_oracle_lon", "cv_holdv0", "v4_oracle", "v1_ego_v0",
         "refc_xl_produced", "v1_tactical_follow", "v1_tactical_oracle",
         "v1_lat_straight", "refc_small_produced", "refc_base_produced",
         "nospeed_tactical_oracle", "v4_blind", "v1_ego_half",
         "v1_ego_double", "oracle_lon_straight", "stand_still",
         "refc_xl_v0on", "refc_xl_v0off", "refc_base_v0on", "refc_base_v0off"]

PAIRS = [
    ("v1_ego_v0", "v1_tactical_follow", "PRIMARY -- the pre-registered contrast"),
    ("v1_ego_v0", "cv_holdv0", "vs the bar 0.5705"),
    ("v1_ego_oracle_lon", "v1_tactical_follow", "ORACLE ceiling vs control"),
    ("v1_ego_oracle_lon", "cv_holdv0", "ORACLE ceiling vs the bar"),
    ("v1_ego_oracle_lon", "v4_oracle", ""),
    ("v1_ego_v0", "v1_tactical_oracle", "replication of the primary"),
    ("v1_ego_v0", "nospeed_tactical_oracle", ""),
    ("v1_ego_v0", "v4_oracle", ""),
    ("v1_ego_v0", "refc_xl_produced", ""),
    ("v1_lat_straight", "v1_tactical_follow", "2x2: remove v1's steering"),
    ("cv_holdv0", "v1_lat_straight", "2x2: add the v0 schedule"),
    ("cv_holdv0", "v1_ego_v0", "2x2: shape effect on the v0 schedule"),
    ("v1_ego_half", "v1_tactical_follow", "DEGRADATION -- must be worse"),
    ("v1_ego_double", "v1_tactical_follow", "DEGRADATION -- see report 5.2"),
    ("refc_xl_v0on", "refc_xl_v0off", "BLOCK A -- trained v0 ablated, XL"),
    ("refc_base_v0on", "refc_base_v0off", "BLOCK A -- trained v0 ablated, base"),
    ("refc_xl_v0on", "refc_xl_produced", "BLOCK A fidelity: must reproduce"),
    ("refc_base_v0on", "refc_base_produced", "BLOCK A fidelity: must reproduce"),
    ("refc_xl_v0off", "cv_holdv0", ""),
]


def ci(x, nd=4):
    if not x or x.get("mean") is None:
        return "—"
    return f"{x['mean']:.{nd}f} [{x['lo']:.{nd}f}, {x['hi']:.{nd}f}]"


def delta(blk, comp, sign):
    x = (blk or {}).get(comp)
    if not x or x.get("delta") is None:
        return "—"
    d, lo, hi = x["delta"] * sign, x["lo"] * sign, x["hi"] * sign
    if sign < 0:
        lo, hi = hi, lo
    return f"**{d:+.4f}** [{lo:+.4f}, {hi:+.4f}] {'⭐ SEP' if x['separated'] else 'n.s.'}"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--panel", required=True)
    ap.add_argument("--decomp", required=True)
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    d = json.loads(Path(a.panel).read_text(encoding="utf-8"))
    dec = json.loads(Path(a.decomp).read_text(encoding="utf-8"))["arms"]
    P, A = d["paired"], d["arms"]
    rdf = d.get("_recovery_defined_fraction", {})
    L = []
    L.append("<!-- GENERATED by scripts/summarize.py from the artifacts. "
             "DO NOT hand-edit. -->\n")
    g = d["PANEL_GATE"]
    L.append(f"### Panel gate\n\nadmitted: `{sorted(k for k, v in g['admitted'].items() if v)}` "
             f"· probes excluded from the gate: "
             f"`{g.get('validation_probes_excluded_from_the_gate', [])}`\n")

    L.append("\n### Arm scores (panel-wide gate)\n")
    L.append("| arm | PSS | `ego_progress` | `recovery` | rec. def. frac |")
    L.append("|---|---|---|---|---:|")
    for n in ORDER:
        if n not in A:
            continue
        node, c = A[n], A[n].get("components", {})
        comp = (node.get("composite") or {}).get("ci")
        pss = ci(comp) if comp else "**REFUSED (`VacuousMetric`)**"
        L.append(f"| `{n}` | {pss} | {ci(c.get('ego_progress', {}).get('ci'))} | "
                 f"{ci(c.get('recovery', {}).get('ci'))} | "
                 f"{rdf.get(n, float('nan')):.4f} |")

    L.append("\n### Paired contrasts (episode-cluster bootstrap, B=2000, identical rows)\n")
    L.append("| contrast | Δ PSS (panel gate) | Δ `ego_progress` | Δ `recovery` | per-arm gate | note |")
    L.append("|---|---|---|---|---|---|")
    for x, y, note in PAIRS:
        k, s = f"{x}__minus__{y}", 1
        if k not in P:
            k, s = f"{y}__minus__{x}", -1
        if k not in P:
            continue
        blk = P[k]
        sens = blk.get("_PSS_under_per_arm_gate_SENSITIVITY") or {}
        sv = (f"{sens['delta'] * s:+.4f} {'SEP' if sens.get('separated') else 'n.s.'}"
              if sens.get("delta") is not None else "—")
        L.append(f"| `{x}` − `{y}` | {delta(blk, 'PSS_recovery_progress', s)} | "
                 f"{delta(blk, 'ego_progress', s)} | {delta(blk, 'recovery', s)} | "
                 f"{sv} | {note} |")

    L.append("\n### Lateral / longitudinal decomposition (endpoint error vs the logged path)\n")
    L.append("| arm | along err mean (m) | along \\|err\\| (m) | along RMS (m) | "
             "cross \\|err\\| (m) | longitudinal share of sq. err |")
    L.append("|---|---:|---:|---:|---:|---:|")
    for n in sorted(dec, key=lambda k: dec[k]["along_err_absmean_m"], reverse=True):
        v = dec[n]
        L.append(f"| `{n}` | {v['along_err_mean_m']:+.3f} | {v['along_err_absmean_m']:.3f} | "
                 f"{v['along_err_rms_m']:.3f} | {v['cross_err_absmean_m']:.3f} | "
                 f"{v['longitudinal_share_of_sq_err'] * 100:.1f} % |")

    io.open(a.out, "w", encoding="utf-8", newline="\n").write("\n".join(L) + "\n")
    print(f"[summarize] -> {a.out}  ({len(L)} lines)")
    print("SUMMARIZE_DONE")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
