# GENERATED by refe/proxy_pod_extract.py -- mode index; run with the script on STDIN:
#   nice -n 19 ionice -c3 python3 -B -u -     (writes NOTHING on the pod; the tar goes to stdout)
CFG_B64 = 'eNqFjUEKwjAQRa9SZi1NquDCywxjM8pgmpQkbSPi3U2KigvR7Z/33twgcopoJMChAbX4cIkj9awMJVKBT4yO5hRInPJu9Fb6q6oKbBpYZzwHv/yXP9hihsn9/FnuUc2SbLd/Jzq96pho0u2uVkbJbOO3yMvBJ1LggTIOR6z4Vre6Lt5wlcUZznB/AHTfXeY='

import base64, gzip, hashlib, io, json, os, sys, tarfile, time, zlib
CFG = json.loads(zlib.decompress(base64.b64decode(CFG_B64)).decode("utf-8"))
RATE = float(CFG["max_mb_s"]) * 1e6
T0 = time.time()
ST = {"read": 0, "members": 0}
OUT = sys.stdout.buffer
TAR = tarfile.open(fileobj=OUT, mode="w|", format=tarfile.PAX_FORMAT)
DIG = {}


def log(m):
    sys.stderr.write(time.strftime("%H:%M:%S ") + m + "\n")
    sys.stderr.flush()


def throttle(n):
    ST["read"] += n
    ahead = ST["read"] / RATE - (time.time() - T0)
    if ahead > 0:
        time.sleep(ahead)


class Reader:
    def __init__(self, f):
        self.f, self.h = f, hashlib.sha256()

    def read(self, n=-1):
        b = self.f.read(n)
        self.h.update(b)
        throttle(len(b))
        return b


def add_bytes(name, data):
    ti = tarfile.TarInfo(name)
    ti.size, ti.mtime, ti.mode = len(data), int(time.time()), 0o644
    TAR.addfile(ti, io.BytesIO(data))
    ST["members"] += 1
    DIG[name] = [hashlib.sha256(data).hexdigest(), len(data)]


def add_path(name, path):
    st = os.stat(path)
    ti = tarfile.TarInfo(name)
    ti.size, ti.mtime, ti.mode = st.st_size, int(st.st_mtime), 0o644
    with open(path, "rb") as f:
        r = Reader(f)
        TAR.addfile(ti, r)
    ST["members"] += 1
    DIG[name] = [r.h.hexdigest(), st.st_size]


def lines(path, size):
    """(offset, bytes without the newline) of every COMPLETE line within the first `size` bytes"""
    with open(path, "rb") as f:
        pos, pend, pend_off = 0, b"", 0
        while pos < size:
            chunk = f.read(min(8 << 20, size - pos))
            if not chunk:
                break
            throttle(len(chunk))
            pos += len(chunk)
            data = pend + chunk
            start = 0
            while True:
                nl = data.find(b"\n", start)
                if nl < 0:
                    break
                yield pend_off + start, data[start:nl]
                start = nl + 1
            pend_off += start
            pend = data[start:]


def small_files(done):
    for name, path in (("run/config.json", os.path.join(CFG["run_dir"], "config.json")),
                       ("run/metrics.jsonl", os.path.join(CFG["run_dir"], "metrics.jsonl")),
                       ("bank/calib_table.json", os.path.join(CFG["train_grow"], "calib_table.json"))):
        if os.path.isfile(path):
            add_path(name, path)
        else:
            done.setdefault("missing_small_files", []).append(path)


def index_mode(done):
    sd = CFG["sets_dir"]
    rows = ["file\toffset\tnbytes\tlog_name\ttoken\tstep\trank\tckpt_step\tlabel_version\tok"]
    finfo = ["file\tsize\tmtime\tlines\tbad"]
    files = sorted(fn for fn in os.listdir(sd) if fn.startswith("onpolicy_") and fn.endswith(".jsonl"))
    for fn in files:
        p = os.path.join(sd, fn)
        st = os.stat(p)
        nl = nb = 0
        for off, line in lines(p, st.st_size):
            nl += 1
            try:
                r = json.loads(line)
                if r.get("kind") != "onpolicy_set":
                    raise ValueError("kind")
                rows.append("\t".join(str(x) for x in (fn, off, len(line) + 1, r["log_name"], r.get("token", ""),
                                                        int(r["step"]), int(r.get("rank", 0)), int(r["ckpt_step"]),
                                                        int(r.get("label_version", 1)), 1)))
            except Exception:
                nb += 1
                rows.append("\t".join(str(x) for x in (fn, off, len(line) + 1, "", "", -1, -1, -1, -1, 0)))
        finfo.append("\t".join(str(x) for x in (fn, st.st_size, int(st.st_mtime), nl, nb)))
        log("set file %s: %d lines (%d bad), %.1f MB" % (fn, nl, nb, st.st_size / 1e6))
    add_bytes("index/sets_files.tsv", ("\n".join(finfo) + "\n").encode("utf-8"))
    add_bytes("index/sets_index.tsv", ("\n".join(rows) + "\n").encode("utf-8"))
    krows = ["file\toffset\tnbytes\tlog_name\ttoken\tstep\trank"]
    tinfo = ["file\tsize\tmtime\tlines\tbad"]
    tg = CFG["train_grow"]
    for fn in sorted(os.listdir(tg)):
        if not (fn.startswith("targets_rank") and fn.endswith(".jsonl")):
            continue
        p = os.path.join(tg, fn)
        st = os.stat(p)
        nl = nb = 0
        for off, line in lines(p, st.st_size):
            nl += 1
            try:
                r = json.loads(line)
                krows.append("\t".join(str(x) for x in (fn, off, len(line) + 1, r["log_name"], r.get("token", ""),
                                                         int(r.get("step", 0)), int(r.get("rank", 0)))))
            except Exception:
                nb += 1
        tinfo.append("\t".join(str(x) for x in (fn, st.st_size, int(st.st_mtime), nl, nb)))
        log("train_grow %s: %d rows (%d bad)" % (fn, nl, nb))
    add_bytes("index/train_grow_files.tsv", ("\n".join(tinfo) + "\n").encode("utf-8"))
    add_bytes("index/train_grow_keys.tsv", ("\n".join(krows) + "\n").encode("utf-8"))
    small_files(done)
    done.update({"set_files": len(files), "set_lines": len(rows) - 1, "train_grow_rows": len(krows) - 1})


def extract_mode(done):
    sel = CFG["selection"]
    need = {}
    for ref in sel["images"]:
        need.setdefault(os.path.basename(ref), ref)
    found = {}
    n_walk = 0
    for dp, _dn, fns in os.walk(CFG["pixels"]):
        for fn in fns:
            n_walk += 1
            if fn in need and fn not in found:
                found[fn] = os.path.join(dp, fn)
    log("pixel walk: %d files seen, %d of %d needed found" % (n_walk, len(found), len(need)))
    for b in sorted(need):
        if b in found:
            add_path("pixels/" + need[b], found[b])
    by_file = {}
    for fn, off, nb, key in sel["set_ranges"]:
        by_file.setdefault(fn, []).append((int(off), int(nb), key))
    part, buf, acc, bad, n_ok = 0, [], 0, [], 0
    for fn in sorted(by_file):
        p = os.path.join(CFG["sets_dir"], fn)
        with open(p, "rb") as f:
            for off, nb, key in sorted(by_file[fn]):
                f.seek(off)
                line = f.read(nb)
                throttle(len(line))
                try:
                    r = json.loads(line)
                    ok = (line.endswith(b"\n") and r.get("kind") == "onpolicy_set" and
                          [r["log_name"], r.get("token", ""), int(r["step"]), int(r.get("rank", 0))] == list(key))
                except Exception:
                    ok = False
                if not ok:
                    bad.append([fn, off])
                    continue
                buf.append(line)
                n_ok += 1
                acc += len(line)
                if acc >= (64 << 20):
                    add_bytes("onpolicy/part_%04d.jsonl.gz" % part, gzip.compress(b"".join(buf), 6))
                    part, buf, acc = part + 1, [], 0
    if buf:
        add_bytes("onpolicy/part_%04d.jsonl.gz" % part, gzip.compress(b"".join(buf), 6))
    done.update({"images_needed": len(need), "images_found": len(found),
                 "missing_images": sorted(need[b] for b in need if b not in found),
                 "pixel_files_walked": n_walk, "set_lines_ok": n_ok, "bad_set_lines": bad})


done = {"mode": CFG["mode"], "cfg": {k: v for k, v in CFG.items() if k != "selection"},
        "host": os.uname().nodename if hasattr(os, "uname") else "?", "python": sys.version.split()[0],
        "started_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())}
if CFG["mode"] == "index":
    index_mode(done)
else:
    extract_mode(done)
done.update({"bytes_read": ST["read"], "seconds": round(time.time() - T0, 1), "members": ST["members"],
             "digests": DIG, "finished_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())})
data = json.dumps(done).encode("utf-8")
ti = tarfile.TarInfo("%s/DONE.json" % CFG["mode"])
ti.size, ti.mtime, ti.mode = len(data), int(time.time()), 0o644
TAR.addfile(ti, io.BytesIO(data))
TAR.close()
OUT.flush()
log("DONE %s: %d members, %.1f MB read, %.0f s" % (CFG["mode"], ST["members"], ST["read"] / 1e6, time.time() - T0))
