"""Render TABLES.md from the banked JSONs. NOTHING in TABLES.md is retyped by hand."""
from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
R = json.loads((HERE / "results_event_retune.json").read_text(encoding="utf-8"))
V = json.loads((HERE / "verify_chance_floor.json").read_text(encoding="utf-8"))
F = json.loads((HERE / "results_four_families.json").read_text(encoding="utf-8"))

FRZ = "CELL_w8_L3.0"
KEY = ("CELL_w8_L3.0", "CELL_w8_L1.0", "CELL_w32_L1.0", "CELL_w16_L2.0", "CELL_w1_L1.0",
       "CELL_w4_L1.0")
POWERED = ("lane_change", "intersection")
L: list[str] = []


def w(x=""):
    L.append(x)


def sep(p):
    return " **SEP**" if p.get("separated") else ""


def d3(p, k="event_recall"):
    q = p[k]
    return f"{q['delta']:+.4f} [{q['lo']:+.4f}, {q['hi']:+.4f}]{sep(q)}"


w("# TABLES — is the SHARED sitclf re-tune deployable, and what does it cost?")
w()
w("*Generated by `render_tables.py` from the banked JSONs. Nothing here is retyped.*")
w()
w(f"Substrate `{R['substrate']}` · real score columns are the parent's **banked** "
  f"`CELL_w*_L*` (out-of-fold, 2-fold cluster CV) · alarm budget `top_frac = "
  f"{R['top_frac']}` · event look-back `h_max_s = {R['h_max_s']} s` · "
  f"B = {R['n_boot']} paired episode-cluster draws · pre-registration SHA-1 "
  f"`{R['_prereg_sha1']}`.")
w()
w("⛔ **VISION-ONLY at inference** — every arm reads frozen v1 camera latents and nothing else.")
w()

# ---------------------------------------------------------------- 0. controls
w("## 0. Controls, all resolved before any arm is read")
w()
w("| control | result |")
w("|---|---|")
c = R["C_FID_GRID"]
w(f"| **C-FID-GRID** — re-run the parent's pipeline and compare to its banked columns | "
  f"⚠️ **NOT bit-exact**: max abs diff **{c['max_abs_diff_over_25_cells']:.3e}** over 25 cells "
  f"(`torch.svd_lowrank(niter=4)` on CUDA is not run-to-run deterministic). `eval_rows` and "
  f"`y_lead3` **bit-identical**. Only **{c['alarm_set_rows_moved_total']}** alarm-set rows move "
  f"across 25 cells × 3 situations. ⇒ the real arms below use the parent's **banked** columns "
  f"verbatim, so nothing depends on the drift |")
w(f"| **C-FID-QB** — every headline re-derived by the PROMOTED "
  f"`sitclf_deploy.event_anticipation_report` | "
  f"**{'PASS' if R['C_FID_QB_promoted_stack_fn']['PASS'] else 'FAIL'}** — "
  f"{len(R['C_FID_QB_promoted_stack_fn']['cells'])} cells, "
  f"{len(R['C_FID_QB_promoted_stack_fn']['MISMATCHES'])} mismatches |")
w(f"| **C-FID-FLOOR** — the ANALYTIC chance floor vs this stream's 200-draw SIMULATION | "
  f"**{V['VERDICT'].split(chr(8212))[0].strip()}** — "
  + " · ".join(f"`{s}` {V['situations'][s]['cells'][FRZ]['chance_event_recall_ANALYTIC']:.4f} vs "
               f"{V['situations'][s]['cells'][FRZ]['chance_event_recall_SIMULATED']:.4f}"
               for s in V["situations"]) + " |")
for s in R["per_situation"]:
    d = R["per_situation"][s]
    w(f"| **C-BUDGET** `{s}` — is `n_alarm` identical for every arm? | "
      f"**{'YES' if d['C_BUDGET_all_arms_same_n_alarm'] else 'NO'}** — "
      f"{d['n_alarm']:,} alarms for all {len(d['arms'])} columns |")
w(f"| **C-POW** (INHERITED from the parent's pre-committed count) | "
  + " · ".join(f"`{s}` **{R['per_situation'][s]['n_onset_clusters']}**"
               f"{' ⛔ UNDERPOWERED' if not R['per_situation'][s]['C_POW_pass'] else ''}"
               for s in R["per_situation"]) + " (bar 40) |")
w()

# ------------------------------------------------- 1. the chance floor
w("## 1. ⭐ THE CHANCE FLOOR — the control that fired")
w()
w("*200 uniform-random score columns at the **identical** 5 % rank budget, cross-checked against "
  "an exact hypergeometric expectation computed by the promoted `stack` function (§0).*")
w()
w("| situation | **chance event recall** | 95 % band | **FROZEN** | best cell | "
  "chance alarm prec. @5 s | @3 s |")
w("|---|---:|---|---:|---:|---:|---:|")
for s in R["per_situation"]:
    d = R["per_situation"][s]
    ch = d["C_CHANCE"]
    best = max((n for n in d["arms"] if not n.startswith("NULL_")),
               key=lambda n: d["arms"][n]["event_recall"]["point"])
    w(f"| `{s}` | **{ch['event_recall']['mean']:.4f}** | "
      f"[{ch['event_recall']['p2.5']:.4f}, {ch['event_recall']['p97.5']:.4f}] | "
      f"**{d['arms'][FRZ]['event_recall']['point']:.4f}** | "
      f"{d['arms'][best]['event_recall']['point']:.4f} (`{best}`) | "
      f"{ch['alarm_precision_5s']['mean']:.4f} | {ch['alarm_precision_3s']['mean']:.4f} |")
w()
w("⇒ **every real arm, including the winner, is far BELOW the uniform-random floor on event "
  "recall.** `event_recall` at a fixed GLOBAL budget is maximised by DISPERSING alarms.")
w()

# ------------------------------------------------- 2. the headline table
w("## 2. ⭐ THE DEPLOYABILITY TABLE — precision WITH recall, and BOTH denominators")
w()
w("*`n_alarm` is what precision divides by; `n_pos` is what recall divides by; both are printed. "
  "The chance-referenced **lift** is the axis that dispersion cannot game — a random score sits "
  "at 1.000 on it, so `< 1.000` is a genuine below-chance verdict.*")
w()
for s in POWERED:
    d = R["per_situation"][s]
    w(f"### `{s}` — {d['n_onsets']} onsets in {d['n_onset_clusters']} clusters, "
      f"{d['n_pos_lead3']:,} pos / {d['n_scorable_rows']:,} rows, "
      f"**{d['n_alarm']:,} alarms fixed for every arm**")
    w()
    w("| cell | event recall | warned | alarm prec. @5 s | **@3 s (deployed)** | "
      "**prec.-LIFT @3 s** | frame recall | tp | median lead | ridge params |")
    w("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    for n in KEY:
        a = d["arms"][n]
        op = a["op_5pct_at_deploy_label_3s"]
        lift = V["situations"][s]["cells"].get(n, {}).get("alarm_precision_lift_deploy")
        tag = " ⬅ **DEPLOYED**" if n == FRZ else ""
        w(f"| `{n}`{tag} | {a['event_recall']['point']:.4f} | "
          f"{a['n_onsets_warned']}/{a['n_onsets']} | "
          f"{a['alarm_precision_5s']['point']:.4f} | **{a['alarm_precision_3s']['point']:.4f}** | "
          f"**{lift:.4f}**" + (" ⛔ **< 1**" if lift is not None and lift < 1.0 else "") +
          f" | {op['recall']:.4f} | {op['tp']} | {a['median_lead_s']} s | "
          f"{a['ridge_params']:,} |")
    w()
    w("**Paired deltas vs the deployed cell** (paired episode-cluster bootstrap, "
      f"B = {R['n_boot']}), **beside the SAME cell on clip-permuted features**:")
    w()
    w("| cell | Δ event recall | Δ event recall — **NULL twin** | Δ alarm prec. @5 s | "
      "Δ prec. @5 s — **NULL twin** | Δ prec. @3 s | fold 0 / fold 1 Δ recall |")
    w("|---|---|---|---|---|---|---|")
    for n in KEY:
        if n == FRZ:
            continue
        a, nl = d["arms"][n], d["arms"]["NULL_" + n]
        pv, nv = a["paired_vs_frozen"], nl["paired_vs_frozen"]
        f0 = a["C_FOLD"]["fold0"]["delta_vs_frozen"]
        f1 = a["C_FOLD"]["fold1"]["delta_vs_frozen"]
        flag = "" if (f0 > 0) == (f1 > 0) or f0 == 0 or f1 == 0 else " ⛔ **SIGN FLIP**"
        w(f"| `{n}` | {d3(pv)} | {d3(nv)} | {d3(pv, 'alarm_precision_5s')} | "
          f"{d3(nv, 'alarm_precision_5s')} | {d3(pv, 'alarm_precision_3s')} | "
          f"{f0:+.4f} / {f1:+.4f}{flag} |")
    w()

# ------------------------------------------------- 3. multiplicity
w("## 3. MULTIPLICITY — Holm–Bonferroni over the 24 non-reference cells (pre-registered)")
w()
for s in POWERED:
    d = R["per_situation"][s]
    H = d["HOLM_25_cells"]
    rows = sorted(((H[n]["rank"], n) for n in H))
    w(f"### `{s}` — family size {len(H)}, α = 0.05")
    w()
    w("| # | cell | Δ event recall | one-sided p | Holm threshold | **Holm reject** |")
    w("|---:|---|---|---:|---:|---|")
    for r, n in rows[:10]:
        pv = d["arms"][n]["paired_vs_frozen"]["event_recall"]
        w(f"| {r} | `{n}` | {pv['delta']:+.4f} [{pv['lo']:+.4f}, {pv['hi']:+.4f}] | "
          f"{H[n]['p_one_sided']:.5f} | {H[n]['holm_threshold']:.5f} | "
          f"{'✅ **YES**' if H[n]['holm_reject'] else '❌ no'} |")
    nrej = sum(1 for n in H if H[n]["holm_reject"])
    nsep = sum(1 for n in H if d["arms"][n]["paired_vs_frozen"]["event_recall"]["separated"]
               and d["arms"][n]["paired_vs_frozen"]["event_recall"]["delta"] > 0)
    w()
    w(f"**{nsep} of {len(H)} cells separate above frozen uncorrected; {nrej} survive Holm.**")
    w()

# ------------------------------------------------- 4. oracle + retune
w("## 4. THE ORACLE AND THE RE-TUNE PROCEDURE — each beside its own null")
w()
w("*⭐ `C_ORACLE_POOLED` maximises the **POOLED** delta, i.e. exactly the statistic the arms are "
  "judged by, so it IS an upper bound on any fixed-cell arm — the fix for the parent's "
  "`C-ORACLE-PS`, which maximised a per-fold statistic while the headline was pooled, and "
  "therefore was not a bound and fired under the null.*")
w()
w("| situation | oracle cell | oracle Δ | **NULL oracle cell** | **NULL oracle Δ** | "
  "winner's-curse share |")
w("|---|---|---:|---|---:|---:|")
for s in R["per_situation"]:
    d = R["per_situation"][s]
    o, on = d["C_ORACLE_POOLED"], d["C_ORACLE_POOLED_NULL"]
    share = (on["delta_event_recall"] / o["delta_event_recall"]
             if o["delta_event_recall"] > 0 else float("inf"))
    w(f"| `{s}` | `{o['cell']}` | {o['delta_event_recall']:+.4f} | `{on['cell']}` | "
      f"**{on['delta_event_recall']:+.4f}** | "
      f"{'**' + format(100 * share, '.0f') + ' %**' if share != float('inf') else 'n/a'} |")
w()
w("**`RETUNE_SEL`** — one SHARED cell per fold, selected on the SEL split by the EVENT criterion "
  "(the arm the parent named as missing), evaluated on the test fold:")
w()
w("| arm | fold 0 cell | fold 1 cell | **one cell in both folds?** | `lane_change` Δ recall | "
  "`intersection` Δ recall |")
w("|---|---|---|---|---|---|")
for k, v in R["RETUNE_SEL"].items():
    lc = v["per_situation"]["lane_change"]["paired_vs_frozen"]
    it = v["per_situation"]["intersection"]["paired_vs_frozen"]
    w(f"| `{k}` | `{v['fold0_cell']}` | `{v['fold1_cell']}` | "
      f"{'✅ yes' if v['single_cell_in_both_folds'] else '⛔ **NO — not a deployable setting**'} | "
      f"{d3(lc)} | {d3(it)} |")
w()
w("Onsets available to the SEL-split selector: "
  + " · ".join(f"`{k}` **{v}**" for k, v in R["SEL_split_onsets"].items() if v is not None) + ".")
w()

# ------------------------------------------------- 5. four families
w("## 5. THE FOUR BINDING FAMILIES — per family, never pooled")
w()
w("*CAUSAL ego block (`sitclf_b4_substrate.ego_causal.npz`); the quarantined legacy block is run "
  "beside it so the difference is measured. ⛔ ego is the STRATIFICATION variable only — no arm "
  "reads it as an input.*")
w()
w("### TACTICAL — the manoeuvre decision itself")
w()
w("| situation | arm | AP-lift | vs FROZEN (paired) | P@5 % | recall | n_alarm | n_pos | "
  "median lead |")
w("|---|---|---:|---|---:|---:|---:|---:|---:|")
for key in F["situations"]:
    if "::legacy_ego" in key:
        continue
    s, arm = key.split("::")[0], key.split("::")[1]
    t = F["situations"][key]["families"]["TACTICAL"]
    dd = t["paired_delta_ap_lift"]
    op = t["operating_point_5pct"][arm]
    up = " ⛔ UNDERPOWERED" if s == "roundabout" else ""
    w(f"| `{s}`{up} | `{arm}` | {t['ap_lift'][arm]:.4f} | "
      f"{dd['delta']:+.4f} [{dd['lo']:+.4f}, {dd['hi']:+.4f}]"
      f"{' **SEP**' if dd['separated'] else ''} | {op['precision']:.4f} | {op['recall']:.4f} | "
      f"{op['n_alarm']:,} | {op['n_pos']:,} | "
      f"{t['anticipation_lead'][arm]['median_lead_s']} s |")
w()
for fam in ("LONGITUDINAL", "LATERAL"):
    k0 = [k for k in F["situations"] if "::legacy_ego" not in k][0]
    nc = F["situations"][k0]["families"][fam]["_not_computable"]
    w(f"### {fam} — ⚠️ *not computable as stated* (`{nc}`)")
    w()
    w("*Reason: this arm emits a per-frame situation probability, not a trajectory. What IS "
      "answerable — and what the family exists to force — is whether the change holds across "
      "the regimes, or wins overall while failing exactly where it matters.*")
    w()
    w("| situation | arm | stratum | n rows | n pos | Δ AP-lift vs FROZEN |")
    w("|---|---|---|---:|---:|---|")
    for key in F["situations"]:
        if "::legacy_ego" in key:
            continue
        s, arm = key.split("::")[0], key.split("::")[1]
        if s not in POWERED:
            continue
        for st, v in F["situations"][key]["families"][fam]["strata"].items():
            if v.get("_status") == "UNPOWERED":
                w(f"| `{s}` | `{arm}` | `{st}` | — | — | ⛔ UNPOWERED |")
                continue
            dd = v["paired_delta_ap_lift"]
            w(f"| `{s}` | `{arm}` | `{st}` | {v['n_rows']:,} | {v['n_pos']:,} | "
              f"{dd['delta']:+.4f} [{dd['lo']:+.4f}, {dd['hi']:+.4f}]"
              f"{' **SEP**' if dd['separated'] else ''} |")
    w()
k0 = [k for k in F["situations"] if "::legacy_ego" not in k][0]
strat = F["situations"][k0]["families"]["STRATEGIC"]
w("### STRATEGIC")
w()
w(f"⛔ **{strat['_status']}** — {strat['_reason']} (n = {strat['n_rows']:,} rows).")
w()

# ------------------------------------------------- 6. ego block
w("## 6. The ego block — CAUSAL vs the quarantined LEGACY, measured not asserted")
w()
w("| situation | family | stratum | causal Δ | legacy Δ | shift | shift as % of |causal| |")
w("|---|---|---|---:|---:|---:|---:|")
arm = "CELL_w8_L1.0"
for s in R["per_situation"]:
    ck, lk = f"{s}::{arm}", f"{s}::{arm}::legacy_ego"
    if lk not in F["situations"]:
        continue
    for fam in ("LONGITUDINAL", "LATERAL"):
        for st in F["situations"][ck]["families"][fam]["strata"]:
            cv = F["situations"][ck]["families"][fam]["strata"][st]
            lv = F["situations"][lk]["families"][fam]["strata"][st]
            if cv.get("_status") == "UNPOWERED":
                continue
            dc = cv["paired_delta_ap_lift"]["delta"]
            dl = lv["paired_delta_ap_lift"]["delta"]
            if abs(dc - dl) < 1e-9:
                continue
            pct = 100 * abs(dc - dl) / abs(dc) if abs(dc) > 1e-9 else float("inf")
            up = " ⛔" if s == "roundabout" else ""
            w(f"| `{s}`{up} | {fam} | `{st}` | {dc:+.4f} | {dl:+.4f} | {dc - dl:+.4f} | "
              f"{pct:.1f} % |")
w()

Path(HERE / "TABLES.md").write_text("\n".join(L) + "\n", encoding="utf-8")
print(f"wrote TABLES.md ({len(L)} lines)")
