#!/usr/bin/env python3
"""Insert the D-FEASDEC section into GOALS_AND_CLAIMS.md, idempotently.

⛔ Written as a script rather than an edit because the G: mount flaps: a partial write of a
3,100-line register is worse than a failed one. It reads, verifies the anchor is present
exactly once, writes to a temp file on LOCAL disk, then copies -- and re-reads to confirm.
"""
import io
import os
import shutil
import sys

REG = "G:/Meine Ablage/SayBouBase/raw/Projects/TanitAD/Project Steering/GOALS_AND_CLAIMS.md"
TMP = "C:/Users/Admin/feasdec/raw/_goals_new.md"
ANCHOR = ("## D-REFCV4B-EGODROP2 / H-EGODROP-PRED — the ego-dropout burden MEASURED "
          "on the trained model")
MARK = "## D-FEASDEC — the feasibility-aware decode"

SECTION = """## D-FEASDEC — the feasibility-aware decode: refcv3's driven path made SAFER BY CONSTRUCTION (2026-09-05, Arch+Inference FlyWheel)

Evidence for every row: `TanitAD Research Lab/Deployment & Optimization/Research/2026-09-05-feasible-decode/RESULT.md` (+ `SPEC.md`, `SPEC_ADDENDUM_P1b.md`, `SPEC_ADDENDUM_P1c.md`, `raw/`). Executes `Project Steering/Decisions/2026-09-05-mm-decisions.md` §M23.5 and the successor scoped in `…/2026-09-05-kinematic-gate/SUCCESSOR_FEASIBILITY_AWARE_DECODE.md`. **ZERO GPU, ZERO training, ZERO new parameters.** Tiers: T0 = fan readout · T1 = self-action OPEN loop (PI ruling 2026-09-02).

| id | claim / hypothesis | status | evidence |
|---|---|---|---|
| D-FEASDEC-1 | ⭐⭐ **THE 8.56× IS CLOSED BY CONSTRUCTION, NOT BY A PENALTY: A CONTROL-SPACE PROJECTION MAKES AN ENVELOPE- OR KAMM-VIOLATING PATH UNREPRESENTABLE.** MEASURED 2026-09-05 at zero GPU (`stack/tanitad/refs/feasible_decode.py`, 15 unit pins; 400 EVAL windows × 128 candidates / 70 episodes, npz md5 `9bda7715a657…`). The projection inverts the EXACT finite-difference map `fan_safety.score_paths` uses, clamps `|a| ≤ 4`, `|κ| ≤ 0.2` and projects `(a, a_lat)` radially onto the `μg` friction disc, then re-integrates **sequentially in k** (because `v_mid[k]` depends on `accel[0..k-1]`). At `μ = 0.70` the emitted fan's **`envelope` 0.8879 → 0.0000 EXACTLY** and **`kamm_over` 0.8408 → 0.0000 EXACTLY** — a STRUCTURAL ZERO, an identity no seed or bootstrap can move (`H-ECHO-4` precedent) — with `fan_peak_g` **4.1789 → 0.5964 g**, i.e. **96.87 % of the D1 = 3.6981 g gap**, and the bank ratio **8.69× → 1.24×**. ⭐ The pre-registered `+entry` variant (which also binds the first step's speed to `v0 ± a_max·dt`) drives **`fan_infeasible` 0.8916 → 0.0000 exactly over all 51,200 candidates**, and that is an ARITHMETIC IDENTITY rather than a lucky draw: the entry clamp contributes `a_max·dt = 2.0` and the accel clamp `a_max·dt·mean(0,1,2,3) = 3.0`, summing to exactly the reachability band's `A_MAX_REACH·horizon = 5.0 m/s`. ⛔ **P2-C4 FAILS for the headline arm as committed**: `off_reach` 0.1094 → 0.3405 (+0.2311 vs a +0.05 bar); only the `+entry` variant removes it (0.0000). ⛔ It is applied at EVERY pass that moves a waypoint (`refc.py` `x = bank + offset` AND each `x = x_in + off`) — a penalty on `out["offset"]` reaches one of three. Controls all PASS: disabled lever returns the SAME OBJECT; an already-feasible path is a fixed point (0.00e+00 m); the frozen bank reproduces `bank_vs_fan_feasibility.json`'s bank block written by a DIFFERENT script on a DIFFERENT draw (`peak_g` 0.480782 vs 0.480782) | **SUPPORTED (MEASURED 2026-09-05, T0)** — supersedes the "feasibility-aware offset" work item opened by `D-REFC-OFFSET-FEAS-1` | `…/2026-09-05-feasible-decode/RESULT.md` §2, `raw/mu_frontier.json`, `stack/tanitad/refs/feasible_decode.py`, `stack/tests/test_feasible_decode.py` |
| D-FEASDEC-FRONTIER-1 | ⭐⭐ **THE INFEASIBLE COMPONENT OF refcv3's 9.29 m DISPLACEMENT IS NOT A TRADE AGAINST ACCURACY — IT IS WASTE: REMOVING IT MOVES THE FAN CLOSER TO THE HUMAN.** MEASURED 2026-09-05 on the SAME npz and the SAME 400 windows as the sibling's λ-frontier, both frontiers computed in ONE script so the comparison is not cross-script. At **matched `fan_peak_g`**, the projection's oracle-in-fan ADE change is **−0.0103 m** where the ISOTROPIC SHRINK (`bank + λ(fan − bank)`) costs **+0.7680 m** — a ratio of **−0.013** against a committed bar of < 0.5×, and oracle-in-fan improves **0.2063 → 0.1962 m (−4.9 %)**. ⛔ **THE SCOPE RULE THIS ROW EXISTS TO STATE: the λ-frontier's verdict is about the SHRINK family and cannot be quoted against a PROJECTION.** A shrink removes displacement everywhere; a projection removes only the infeasible COMPONENT of the control profile and keeps the rest. Quoting one against the other is the `df` / Thor `free` / `step_s` scope error in a geometry costume. ⭐ The λ column here reproduces the sibling's independently written `displacement_frontier.py` ROW FOR ROW — a different script, a different author, the same object — which is the object control that `λ = 1 reproduces the fan` structurally cannot give (RETRACTION #30) | **SUPPORTED (MEASURED 2026-09-05, T0)** | `…/2026-09-05-feasible-decode/RESULT.md` §2.1, `raw/mu_frontier.json`; cf. `…/2026-09-05-kinematic-gate/raw/displacement_frontier.json` |
| D-FEASDEC-T1-1 | ⭐⭐ **AT T1 THE DRIVEN PATH IS MEASURABLY SAFER AND THE WHOLE COST IS 1.2 MILLIMETRES.** MEASURED 2026-09-05, `taniteval/tools/paired_openloop.py`, **T1 self-action OPEN loop**, **4,823 windows / 141 episodes**, 0 dropped, `void: false`, all six gates pass, GT and `v0` bit-identical across dumps, paired **episode-cluster bootstrap** (n_boot 2,000, seed 0), floor `ha0`. ⛔ `overlapping_holdout_se` never used. **Driven-path safety: `envelope` 0.0865 → 0.0000, `kamm_over` 0.0021 → 0.0000, `infeasible` 0.0865 → 0.0000 (structural zeros); `peak_g` 0.1415 → 0.1279 (−9.6 %).** For scale the HUMAN's own logged path reads `envelope` **0.0068** — the base arm violates **12.7×** as often as the human, and after the projection it violates LESS often than the human, because it cannot. **The four families, per family, never pooled:** ADE `ade_m` **+0.0012 [0.0002, 0.0024] separated** (30× smaller than the RL arm's +0.0362 failure), `fde_m` +0.0014 ns; ⭐ LONGITUDINAL improves and separates — `LON_speed_mae_mps` **−0.0020 [−0.0036, −0.0008]**, `LON_accel_mae_mps2` **−0.0059 [−0.0105, −0.0023]**, `LON_along_mae_m` +0.0008 ns; ⭐⭐ LATERAL is SPLIT and carries the headline — **`LAT_yaw_rate_mae_radps` 0.2176 → 0.0428, Δ −0.1749 [−0.2563, −0.1087] separated = −80.3 %**, taking the arm from a margin of **+0.1700 (WORSE than a constant-velocity straight line)** to **−0.0049 (better than it)**, while `LAT_cross_mae_m` +0.0009 separated worse and `LAT_heading_mae_deg` −0.0078 ns; TACTICAL `TAC_traj_lat_correct` +0.0004 ns, `TAC_traj_lon_correct` +0.0002 ns; STRATEGIC `STR_route_correct` Δ **0.0000 exactly**. ⚠️ **TACTICAL-declared and STRATEGIC read exact zeros BY CONSTRUCTION, not by measurement** — the projection changes waypoints, and those heads read logits it never touches; that is an identity and must not be read as evidence of anything. ⚠️ **The ADE cost sits at the edge of detectability and the `separated` bit is implementation-sensitive there**: the binding instrument reads [0.0002, 0.0024] separated; this package's own direct read of the same delta on the same windows reads [0.0000, 0.0024] not separated. The binding instrument's answer is the one reported | **SUPPORTED (MEASURED 2026-09-05, T1)** ⛔ scope: the measured arm projects the EMITTED fan with the selector's ranking unchanged; the in-decoder wiring is implemented and unit-pinned but needs one ~1.5 h GPU forward to measure, and the 4060 is saturated | `…/2026-09-05-feasible-decode/RESULT.md` §3, `raw/paired_proj07_vs_base.{json,md}`, `raw/derived_dump_report.json` |
| D-FEASDEC-FLOOR-1 | ⭐ **THE ZERO-LEVER FLOOR IS BIT-IDENTICAL, WHICH IS STRICTLY STRONGER THAN `ctrl0`.** `H-ESTIM-SEED-1` and the `ctrl0` (lr = 0) rule exist because **AdamW normalises by the gradient's own scale**, so a control that zeroes a LOSS still moves all 71 tensors and separated 35 of 57 metrics. This lever takes **ZERO gradient steps**: the arms differ by a deterministic geometric function of the emitted path. MEASURED: the identical derivation pipeline with the lever DISABLED reproduces the base arm on **4,823 / 4,823 windows bit-identically, max \\|Δ\\| = 0.0 exactly**, independently confirmed by `paired_openloop`'s own degeneracy profile (`base:os identical to projoff:os 4823/4823`); and the projection is bit-identical under a different `torch` seed. ⇒ the rig's run-to-run noise floor is **EXACTLY 0**, which no `ctrl0` can improve on. ⚠️ **SCOPE, STATED: this retires the TRAINING-variance question for THIS arm only.** Any future arm that FINE-TUNES the decoder under the projection re-acquires `H-ESTIM-SEED-1` in full, and nothing here discharges it in advance | **SUPPORTED (MEASURED 2026-09-05)** | `…/2026-09-05-feasible-decode/RESULT.md` §3.3, `raw/derived_dump_report.json`, `raw/paired_projoff_vs_base.md` |
| D-PROG-RANK-FIX-1 | ⛔ **`progress` CAN BE MADE TO RANK VIOLATION LOWER, AND EVERY SINGLE-SCALAR RESHAPE TRIED FAILED THE PROGRESS BAR — REPORTED AS COMMITTED.** MEASURED 2026-09-05, per-window Spearman over a window's own 128 candidates, episode-cluster bootstrap (n_boot 4,000, seed 11) — the SAME estimator and seed as `D-RL-REWARD-RANK-1` — on TWO independent draws (240 w / 121 ep and 400 w / 70 ep) that agree on every conclusion with no sign flip and no bar crossing. **P1-C1 PASS:** `progress_v2 = min(along/ref, 1)·1/(1+ex/ex_s)` reads ρ(`peak_g`) **−0.5897 [−0.6707, −0.5002]** from **+0.2900**, ρ(`ttc_below`) **−0.1820** from +0.4697, and carries the COMPOSED default reward from **−0.4603 to −0.6898** — ~86 % of what deleting `progress` entirely would buy, while keeping a progress term. ⛔ **P1-C2 FAIL:** on 160 straight windows its argmax candidate covers **18.672 m** vs argmax-`progress_v1`'s **26.216 m**, ratio **0.7123** below the committed 0.95 (it does clear the driving floors — v0-hold 17.229 m, human 16.624 m on the GT-carrying draw). ⛔ **P1b FAIL on both draws:** `progress_v3` (credit the distance AFTER the feasible projection) reads **+0.5042 / +0.5135**, WORSE than stock — mechanism: `along` is NET +x, so a candidate that swings sideways is penalised by its own lateral excursion, and the projection STRAIGHTENS exactly those candidates so their +x RISES. **The projection is the right fix for the DECODE and the wrong fix for this REWARD TERM.** ⇒ the successor is structural (a longitudinal PAIR), scoped not started | **FAIL as committed (MEASURED 2026-09-05, T0)** — P1-C1 passes, P1-C2 and P1b fail; no goalpost moved | `…/2026-09-05-feasible-decode/RESULT.md` §4, `raw/progress_rank_fix_240w.json`, `raw/progress_rank_fix_400w.json`, `SPEC_ADDENDUM_P1b.md` |
| D-PROG-DISSOLVE-1 | ⭐⭐ **ON A FEASIBILITY-AWARE DECODE THE REWARD-RANKING DEFECT HAS NO POPULATION LEFT: ρ AGAINST `envelope` IS UNDEFINED ON 400/400 WINDOWS.** `D-RL-REWARD-RANK-1` asks whether the reward ranks envelope-VIOLATING candidates above feasible ones, which presupposes windows containing both. MEASURED 2026-09-05: after the projection the fan's `envelope` and `kamm_over` are 0.0000 exactly, so the per-window Spearman is **UNDEFINED — reported as undefined on every window, never averaged in as a null**. **P1c-C0 PASS.** ⛔ **P1c-C1 FAIL:** the WEAKER residual question — does the reward still prefer the harder-driving candidate INSIDE a feasible fan — reads ρ(progress, `peak_g`) **+0.3232 [+0.2229, +0.4115]**, essentially unchanged from the emitted fan's +0.3130. ⇒ **the SAFETY-grade defect is removed by the decode; a COMFORT-grade preference survives and a reward change is still owed.** ⚠️ Different stakes, never one number: preferring 0.6 g over 0.3 g is margin, preferring 4 g over 0.5 g was a safety defect. ⭐ The composed DEFAULT reward's ρ(`peak_g`) collapses **−0.4558 → −0.0611** on the projected fan, i.e. its apparent "good ranking" was largely it DETECTING violations that a fixed decode no longer produces. ⭐ P1c-C3's committed prediction held (the projection does not touch lead geometry; ρ vs `ttc_below` moved 0.4431 → 0.4123, \\|Δ\\| 0.031) — a control that read its predicted value | **P1c-C0 SUPPORTED / P1c-C1 FAIL (MEASURED 2026-09-05, T0)** | `…/2026-09-05-feasible-decode/RESULT.md` §4, `raw/projected_fan_rank_400w.json`, `SPEC_ADDENDUM_P1c.md` |
| H-PROG-SAT-1 | **REFUTED: the additive `feasibility` weight is NOT a null lever because the term is saturated.** Predicted before running: median within-window IQR of `feasibility` over a window's 128 candidates **< 0.05**. MEASURED **0.2440** (240 w) and **0.2262** (400 w) — the term discriminates fine; 26.3 % of candidates read < 0.01 but the bulk does not. ⇒ `feasibility ×4` moving ρ(envelope) by 0.001 is NOT a saturation artifact, and the 270× arithmetic stands on a different mechanism: the composed reward is ALREADY dominated by anti-violation terms, so adding more of one changes few ranks | **REFUTED (MEASURED 2026-09-05)** | `…/2026-09-05-feasible-decode/RESULT.md` §4.1, `raw/progress_rank_fix_240w.json` |
| D-FEASDEC-STOPSTEP-1 | ⛔⛔ **A PATH THAT STOPS INSIDE THE WINDOW IS READ AS A HARD TURN BY *BOTH* OF THE PROGRAMME'S RECOVERIES — `atan2(0,0) == 0` IS A HEADING, NOT AN "UNDEFINED".** MEASURED 2026-09-05: the first build left **2 of 51,200** fan candidates violating `envelope` under `clamp_entry`, both in `v0 = 0.000` windows with speeds `[2.00, 4.00, 2.00, 0.00]`, reading **\\|κ\\| = 0.3396** against a 0.2 cap — a stationary vehicle performing a hard turn. ⚠️ **The comfortable hypothesis ("a scorer artifact, not a leak") was REFUTED by its own discriminator:** `models.kinematic.unicycle_controls_from_path`, the programme's OTHER and EXPLICITLY GUARDED recovery, reads the same 0.3396, because both substitute a DIRECTION for a non-moving step instead of propagating the previous one. A second **implementation** (not the same probe re-run) is what settled it, and it settled it against the comfortable answer. **Fix:** hold the heading through a stop, emit the halted step with length `\\|p\\|·1e-3` (exact, because `atan2` is scale-invariant) and FREEZE the yaw there (`yaw_rate = v·κ`; a stationary vehicle does not turn). After: **0/51,200 on both arms, exact.** ⛔⛔ **AND THE FIX WAS WRONG TWICE IN THE SAME FAMILY:** (1) a **1e-6 m** held step is exact in float64 and NOISE in float32 — at a 4 m offset fp32 resolves ~4.8e-7 m — and the fixture still read `envelope = 1.0` in fp32 while reading a clean 0 in float64 ⇒ **the contract is what the fp32 CONSUMER recovers, never what our float64 arithmetic believes**; (2) a **1 mm ABSOLUTE** threshold then INFLATED slow-but-moving paths (a `ha0` hold at v0 = 0.0005 m/s takes well-conditioned 0.25 mm steps) and drove the round-trip control from 0.00e+00 to **2.63e-03 m** ⇒ "degenerate" is a statement about a step RELATIVE TO ITS OWN PATH; a fixed constant right at one scale and wrong at another is the `df` / `step_s` family **introduced by the fix for another instance of it**. ⭐ Sibling of the same class, kept because it is load-bearing: `score_paths` flags with a strict `>`, so clamping EXACTLY to `a_max` saturates on the boundary and an fp32 round-trip lands above it ~half the time — MEASURED `envelope = 0.609375` on a 64-candidate fixture, which would have read as "the projection leaks". A 1 % margin removes it | **SUPPORTED (MEASURED 2026-09-05)** — pinned by `tests/test_feasible_decode.py::test_a_stop_inside_the_window_does_not_manufacture_a_turn` | `…/2026-09-05-feasible-decode/RESULT.md` §5, `raw/stopped_step_residual.json`, `stack/tanitad/refs/feasible_decode.py` |
| D-FEASDEC-SPECERR-1 | ⚠️ **A CLAIM IN THIS PACKAGE'S OWN SPEC WAS WRONG, AND ITS OWN DELIBERATE NO-OP CONTROL CAUGHT IT.** SPEC §1 claimed that ANY per-window monotone renormalisation of `along` moves the per-window Spearman by exactly zero, and therefore that every "re-normalise progress" proposal is a provable no-op. MEASURED: **true of the UNCLAMPED ratio (0.00e+00, exact) and FALSE of the clamped component (0.0234)** — the `[-1, 1.5]` clamp is NOT monotone: it creates TIES, and a Spearman moves when ties move. ⭐ The cap's tie-making is itself the measured half of the P1 lever: `progress_v2` with the CAP ONLY reads ρ(`peak_g`) **+0.1294** from +0.2900, i.e. the cap alone more than halves the correlation purely by creating ties. ⇒ **a structural claim about a metric must name the exact object it is true of** — ratio vs clamped component — and the control that confirms a predicted no-op is worth running precisely because it can refute the prediction | **CORRECTED IN THE SAME TURN (MEASURED 2026-09-05)** | `…/2026-09-05-feasible-decode/RESULT.md` §4.1, `raw/progress_rank_fix_240w.json` (`no_op_claim` block) |

"""


def main():
    if not os.path.isfile(REG):
        print("REGISTER NOT READABLE -- mount down; not writing")
        return 2
    s = io.open(REG, encoding="utf-8").read()
    if len(s) < 100000:
        print("REGISTER READ SHORT (%d bytes) -- refusing to write" % len(s))
        return 3
    if MARK in s:
        print("already present -- no-op")
        return 0
    if s.count(ANCHOR) != 1:
        print("anchor found %d times -- refusing" % s.count(ANCHOR))
        return 4
    out = s.replace(ANCHOR, SECTION + ANCHOR, 1)
    io.open(TMP, "w", encoding="utf-8", newline="\n").write(out)
    for i in range(8):
        try:
            shutil.copyfile(TMP, REG)
            back = io.open(REG, encoding="utf-8").read()
            if MARK in back and len(back) == len(out):
                print("WROTE ok on attempt %d: %d -> %d bytes, +%d rows"
                      % (i + 1, len(s), len(back), SECTION.count("\n| D-") +
                         SECTION.count("\n| H-")))
                return 0
        except Exception as e:      # noqa: BLE001
            print("attempt %d failed: %s" % (i + 1, e))
    print("COULD NOT VERIFY THE WRITE -- treat as INCONCLUSIVE")
    return 5


if __name__ == "__main__":
    sys.exit(main())
