"""Every table in TABLES.md, generated from the JSONs. NOTHING is retyped by hand.

A retyped table is how a number drifts away from its artifact; the programme has already retracted
counts that were transplanted between streams. Run this after the study and the four-family
re-analysis, and TABLES.md is a pure function of the banked JSONs.

usage:
  python render_tables.py --results results_horizon_ps.json \
      --families results_four_families.json --ego ego_leak_audit.json --out TABLES.md
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

SITS = ("intersection", "lane_change", "roundabout")


def ci(d, k="delta", star=True):
    if d is None:
        return "—"
    s = f"{d[k]:+.4f} [{d['lo']:+.4f}, {d['hi']:+.4f}]"
    if star and d.get("separated"):
        s += " **SEP**"
    return s


def pt(d):
    return f"{d['point']:.4f} [{d['lo']:.4f}, {d['hi']:.4f}]"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default="results_horizon_ps.json")
    ap.add_argument("--families", default="results_four_families.json")
    ap.add_argument("--ego", default="ego_leak_audit.json")
    ap.add_argument("--out", default="TABLES.md")
    a = ap.parse_args()
    R = json.loads(Path(a.results).read_text(encoding="utf-8"))
    FAM = (json.loads(Path(a.families).read_text(encoding="utf-8"))
           if Path(a.families).exists() else None)
    EGO = (json.loads(Path(a.ego).read_text(encoding="utf-8"))
           if Path(a.ego).exists() else None)
    L = []
    W = L.append

    W("# TABLES — per-situation `(window, lead_s)` vs the single frozen setting")
    W("")
    W("*Generated by `render_tables.py` from the banked JSONs. Nothing here is retyped.*")
    W("")
    W(f"Substrate `{R['substrate']}` · eval rows **{R['eval_rows']}** · "
      f"Q-A label **{R['eval_label_qa']}** · frozen cell "
      f"**W={R['frozen_cell']['win']}, L={R['frozen_cell']['lead_s']} s** · "
      f"B = {R['n_boot']} paired episode-cluster draws.")
    W("")

    # ---------------- controls -------------------------------------------------------
    W("## 0. Controls, all resolved BEFORE any arm is read")
    W("")
    W("| control | result |")
    W("|---|---|")
    cf = R.get("C_FID_PARENT")
    if isinstance(cf, dict):
        det = " · ".join(f"`{s}` AP {v['ap']} vs {v['want_ap']} "
                         f"({'MATCH' if v['MATCH'] else 'MISMATCH'})"
                         for s, v in cf["per_situation"].items())
        W(f"| **C-FID-PARENT** — reproduce the sibling stream's banked lead-3.0 row | "
          f"**{cf['C_FID_PARENT']}** — {det} |")
    W(f"| **C-FID-RIDGE** — the λ-swept path vs `stack`'s `sitclf.ridge_scores` | "
      f"max abs diff **{max(R['C_FID_RIDGE_max_abs_diff'].values()):.1e}** at every window "
      f"({', '.join(f'{k} {v:.0e}' for k, v in R['C_FID_RIDGE_max_abs_diff'].items())}) |")
    cp = " · ".join(f"`{s}` **{v['n_clusters_with_a_positive']}**"
                    f"{'' if v['C_POW_pass'] else ' ⛔ UNDERPOWERED'}"
                    for s, v in R["C_POW"].items())
    W(f"| **C-POW** — positive clusters, counted to disk before any score was read (bar "
      f"{list(R['C_POW'].values())[0]['bar']}) | {cp} |")
    for s in SITS:
        if s not in R["per_situation"]:
            continue
        q = R["per_situation"][s]["QA_TRAIN_HORIZON"]
        W(f"| **C-SEL-NULL** on `{s}` — the same per-situation selection run on "
          f"clip-permuted features | {ci(q['C_SEL_NULL'])} |")
    W("")

    # ---------------- the headline ---------------------------------------------------
    W("## 1. ⭐ THE HEADLINE — does a per-situation `(W, L)` beat the frozen one?")
    W("")
    W("| situation | pos clusters | **VERDICT** | `PS-SEL` − `FROZEN` | `C-ORACLE-PS` − `FROZEN` "
      "(⛔ cheats, upper bound) | `PS-SEL` − `C-GLOBAL` | MDE (widest / median) |")
    W("|---|---:|---|---|---|---|---|")
    for s in SITS:
        if s not in R["per_situation"]:
            continue
        p = R["per_situation"][s]
        q = p["QA_TRAIN_HORIZON"]
        W(f"| `{s}` | {p['C_POW']['n_clusters_with_a_positive']} | **{p['VERDICT']}** | "
          f"{ci(q['arms']['PS_SEL']['paired_vs_frozen'])} | "
          f"{ci(q['arms']['C_ORACLE_PS']['paired_vs_frozen'])} | "
          f"{ci(q['PS_SEL_vs_C_GLOBAL'])} | "
          f"{q['mde_widest_ci95']:.4f} / {q['mde_median_ci95']:.4f} |")
    W("")
    W("**Configurations the selection procedure actually chose** (out-of-fit, per fold):")
    W("")
    W("| arm | " + " | ".join(f"fold{f} `{s}`" for f in (0, 1) for s in SITS) + " |")
    W("|---|" + "---|" * 6)
    for arm in ("FROZEN", "PS_SEL", "C_GLOBAL", "C_ORACLE_PS", "NULL_PS_SEL"):
        if arm not in R["arm_configurations"]:
            continue
        c = R["arm_configurations"][arm]
        cells = []
        for f in (0, 1):
            for s in SITS:
                k = f"fold{f}.{s}"
                cells.append(f"W{c[k]['win']}, L{c[k]['lead_s']}s" if k in c else "—")
        W(f"| `{arm}` | " + " | ".join(cells) + " |")
    W("")

    # ---------------- Q-A grid -------------------------------------------------------
    W("## 2. Q-A · TRAIN-HORIZON — the full 5×5 grid against the frozen cell")
    W("")
    W("*Evaluation label frozen at `lead_s = 3.0`; `L` moves the head's TRAINING target only. "
      "Every cell is paired against `FROZEN` on identical rows.*")
    W("")
    for s in SITS:
        if s not in R["per_situation"]:
            continue
        p = R["per_situation"][s]
        q = p["QA_TRAIN_HORIZON"]
        pw = "" if p["C_POW"]["C_POW_pass"] else " ⛔ **UNDERPOWERED_C_POW — decides nothing**"
        W(f"### `{s}` — {q['n_pos']:,} pos / {q['n_scorable']:,} rows, "
          f"{q['n_clusters_with_a_positive']} positive clusters{pw}")
        W("")
        W("| W \\ L | " + " | ".join(f"{L} s" for L in R["grid"]["leads_s"]) + " |")
        W("|---|" + "---|" * len(R["grid"]["leads_s"]))
        for Wn in R["grid"]["wins"]:
            row = []
            for Ln in R["grid"]["leads_s"]:
                k = f"CELL_w{Wn}_L{Ln}"
                d = q["arms"][k]["paired_vs_frozen"]
                mark = " ⬅ FROZEN" if (Wn == R["frozen_cell"]["win"]
                                       and Ln == R["frozen_cell"]["lead_s"]) else ""
                row.append(f"{d['delta']:+.3f} [{d['lo']:+.3f},{d['hi']:+.3f}]"
                           f"{'**SEP**' if d['separated'] else ''}{mark}")
            W(f"| **{Wn}** | " + " | ".join(row) + " |")
        W("")
        W(f"Cells separating **ABOVE** frozen: "
          f"**{q['grid_cells_separating_ABOVE_frozen'] or 'NONE'}**. "
          f"Frozen AP-lift {q['arms']['FROZEN']['point']:.4f} "
          f"[{q['arms']['FROZEN']['lo']:.4f}, {q['arms']['FROZEN']['hi']:.4f}]; "
          f"skill over its own permuted-feature null "
          f"{ci(q['arms']['FROZEN'].get('paired_vs_own_null'))}.")
        W("")

    # ---------------- P2: precision WITH recall, both denominators -------------------
    W("## 3. ⭐ PRECISION **WITH** RECALL, AND BOTH DENOMINATORS (binding)")
    W("")
    W("*A previous report published `brake_stop 0.026 → 0.503, a free win` on the wrong "
      "denominators, with no precision (0.2340 → 0.1711, 380 fires for 153 true) and not separated. "
      "Never that shape again: `n_alarm` is what precision divides by, `n_pos` is what recall "
      "divides by, and both are printed.*")
    W("")
    W("| situation | arm | precision | recall | **n_alarm** (prec. denom.) | **n_pos** (recall "
      "denom.) | tp | base rate | precision-lift |")
    W("|---|---|---:|---:|---:|---:|---:|---:|---:|")
    for s in SITS:
        if s not in R["per_situation"]:
            continue
        q = R["per_situation"][s]["QA_TRAIN_HORIZON"]
        for arm in ("FROZEN", "PS_SEL", "C_GLOBAL", "C_ORACLE_PS"):
            o = q["arms"][arm]["op_5pct"]
            W(f"| `{s}` | `{arm}` | **{o['precision']:.4f}** | {o['recall']:.4f} | "
              f"{o['n_alarm']:,} | {o['n_pos']:,} | {o['tp']:,} | {o['base_rate']:.5f} | "
              f"{o['precision_lift']:.3f} |")
    W("")

    # ---------------- Q-B ------------------------------------------------------------
    W("## 4. Q-B · DEPLOY-HORIZON — the horizon-agnostic EVENT yardstick")
    W("")
    W("*Budget-matched: `n_alarm` is identical for every arm by construction (top 5 % by rank). "
      "An onset is `warned` iff an alarm falls in the 5 s before it. `n_onsets` is fixed across "
      "arms and is the recall denominator.*")
    W("")
    for s in SITS:
        if s not in R["per_situation"]:
            continue
        p = R["per_situation"][s]
        b = p["QB_DEPLOY_HORIZON"]
        pw = "" if b["C_POW_pass"] else " ⛔ **UNDERPOWERED — decides nothing**"
        W(f"### `{s}` — {b['n_onsets']} scorable onsets in "
          f"{b['n_onset_bearing_clusters']} clusters{pw}")
        W("")
        W("| arm | event recall | warned / onsets | alarm precision @5 s | @3 s (deployed) | "
          "median lead (s) | Δ event recall vs FROZEN |")
        W("|---|---|---:|---|---|---|---|")
        for arm in ("FROZEN", "PS_SEL", "C_GLOBAL", "C_ORACLE_PS"):
            e = b["arms"][arm]
            dv = e.get("paired_vs_frozen")
            W(f"| `{arm}` | {pt(e['event_recall'])} | "
              f"{e['n_onsets_warned']}/{e['n_onsets']} | {pt(e['alarm_precision_5s'])} | "
              f"{pt(e['alarm_precision_3s'])} | {pt(e['median_lead_s'])} | "
              f"{ci(dv['event_recall']) if dv else '—'} |")
        W("")
        W("**Per-lead sweep at the frozen window** (the row the per-situation claim lives or dies "
          "on — does this situation prefer a different horizon?):")
        W("")
        W("| cell | event recall | alarm prec. @5 s | median lead (s) | Δ event recall vs FROZEN |")
        W("|---|---|---|---|---|")
        for Ln in R["grid"]["leads_s"]:
            k = f"CELL_w{R['frozen_cell']['win']}_L{Ln}"
            e = b["arms"][k]
            dv = e.get("paired_vs_frozen")
            mark = " ⬅ FROZEN" if Ln == R["frozen_cell"]["lead_s"] else ""
            W(f"| W{R['frozen_cell']['win']}, L{Ln}s{mark} | {pt(e['event_recall'])} | "
              f"{pt(e['alarm_precision_5s'])} | {pt(e['median_lead_s'])} | "
              f"{ci(dv['event_recall']) if dv else '—'} |")
        W("")
        W(f"Grid cell maximising event recall: **`{b['best_grid_cell_by_event_recall']}`**.")
        W("")

    # ---------------- four families --------------------------------------------------
    W("## 5. THE FOUR BINDING FAMILIES — per family, never pooled")
    W("")
    if FAM is None:
        W("*`results_four_families.json` absent — not rendered.*")
    else:
        W(f"*{FAM['_ego_block']}*")
        W("")
        W("### TACTICAL — manoeuvre decision + goal-setting")
        W("")
        W("| situation | arm | AP-lift | vs FROZEN | P@5 % | recall | n_alarm | n_pos | "
          "median lead (s) |")
        W("|---|---|---:|---|---:|---:|---:|---:|---:|")
        for key, rep in FAM["situations"].items():
            if key.endswith("::legacy_ego"):
                continue
            s, arm = key.split("::")
            t = rep["families"]["TACTICAL"]
            o = t["operating_point_5pct"][arm]
            W(f"| `{s}` | `{arm}` | {t['ap_lift'][arm]:.4f} | "
              f"{ci(t['paired_delta_ap_lift'])} | {o['precision']:.4f} | {o['recall']:.4f} | "
              f"{o['n_alarm']:,} | {o['n_pos']:,} | "
              f"{t['anticipation_lead'][arm]['median_lead_s']} |")
        W("")
        W("### LONGITUDINAL and LATERAL — decision quality STRATIFIED BY REGIME")
        W("")
        first = next(iter(FAM["situations"].values()))
        for fam in ("LONGITUDINAL", "LATERAL"):
            blk = first["families"][fam]
            W(f"**{fam}** — ⚠️ *not computable as stated:* `{blk.get('_not_computable','—')}`; "
              f"reason: *{blk.get('_not_computable_reason','—')}*. What IS answerable is whether "
              f"the change holds across regimes:")
            W("")
            W("| situation | arm | stratum | n rows | n pos | Δ AP-lift vs FROZEN |")
            W("|---|---|---|---:|---:|---|")
            for key, rep in FAM["situations"].items():
                if key.endswith("::legacy_ego"):
                    continue
                s, arm = key.split("::")
                if arm != "PS_SEL":
                    continue
                for nm, v in rep["families"][fam]["strata"].items():
                    if v.get("_status") == "UNPOWERED":
                        W(f"| `{s}` | `{arm}` | {nm} | {v['n_rows']:,} | {v['n_pos']} | "
                          f"⛔ UNPOWERED (n_pos < 20 or n_rows < 200) |")
                    else:
                        W(f"| `{s}` | `{arm}` | {nm} | {v['n_rows']:,} | {v['n_pos']:,} | "
                          f"{ci(v['paired_delta_ap_lift'])} |")
            W("")
        W("### STRATEGIC")
        W("")
        W(f"⛔ **{first['families']['STRATEGIC']['_status']}** — "
          f"{first['families']['STRATEGIC']['_reason']} "
          f"(n = {first['families']['STRATEGIC']['n_rows']:,} rows).")
        W("")

    # ---------------- P4 -------------------------------------------------------------
    if EGO:
        W("## 6. P4 — the B4 substrate's ego block (LEGACY LEAKY), audited over ALL 500 clips")
        W("")
        W(f"The banked `E` block is **{EGO['banked_E_block_is']}** — "
          f"max abs diff vs `causal_pre=False` **{EGO['max_abs_diff_bank_vs_legacy']:.3e}** "
          f"(bit-exact), vs the causal rebuild {EGO['max_abs_diff_bank_vs_causal']:.3e}, over "
          f"{EGO['n_rows']:,} rows / {EGO['n_clips']} clips.")
        W("")
        W("| channel | mean abs change | p99 | max | % of channel scale | rows changed > 1 % |")
        W("|---|---:|---:|---:|---:|---:|")
        for nm, c in EGO["channels"].items():
            W(f"| `{nm}` | {c['mean_abs_change']:.6f} | {c['p99_abs_change']:.6f} | "
              f"{c['max_abs_change']:.6f} | **{c['relative_to_scale_pct']} %** | "
              f"**{100*c['frac_rows_changed_gt_1pct_of_scale']:.1f} %** |")
        W("")
        W("**The consumer** — `sitclf_deploy.regime_strata` stratum boundaries — moves by:")
        W("")
        W("| stratum | rows (causal) | rows (legacy) | reassigned | % |")
        W("|---|---:|---:|---:|---:|")
        for nm, v in EGO["strata_boundary_shift"].items():
            W(f"| `{nm}` | {v['n_rows_causal']:,} | {v['n_rows_legacy']:,} | "
              f"{v['n_rows_reassigned']:,} | {100*v['frac_reassigned']:.3f} % |")
        W("")
    Path(a.out).write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {a.out} ({len(L)} lines)")


if __name__ == "__main__":
    main()
